/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_myWindow (void)
{
  GtkWidget *myWindow;
  GtkWidget *fixed1;
  GtkWidget *entryNom;
  GtkWidget *labelNom;
  GtkWidget *buttonHello;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label2;
  GtkWidget *labelHello;

  myWindow = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (myWindow), _("myFirstExample"));
  gtk_window_set_position (GTK_WINDOW (myWindow), GTK_WIN_POS_CENTER);

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (myWindow), fixed1);

  entryNom = gtk_entry_new ();
  gtk_widget_show (entryNom);
  gtk_fixed_put (GTK_FIXED (fixed1), entryNom, 112, 40);
  gtk_widget_set_size_request (entryNom, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryNom), 8226);

  labelNom = gtk_label_new (_("Votre Nom:"));
  gtk_widget_show (labelNom);
  gtk_fixed_put (GTK_FIXED (fixed1), labelNom, 8, 40);
  gtk_widget_set_size_request (labelNom, 104, 24);
  gtk_misc_set_alignment (GTK_MISC (labelNom), 0.5, 0.49);

  buttonHello = gtk_button_new ();
  gtk_widget_show (buttonHello);
  gtk_fixed_put (GTK_FIXED (fixed1), buttonHello, 96, 96);
  gtk_widget_set_size_request (buttonHello, 96, 48);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (buttonHello), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label2 = gtk_label_new_with_mnemonic (_("Say Hello!"));
  gtk_widget_show (label2);
  gtk_box_pack_start (GTK_BOX (hbox1), label2, FALSE, FALSE, 0);

  labelHello = gtk_label_new (_("Hello!"));
  gtk_widget_show (labelHello);
  gtk_fixed_put (GTK_FIXED (fixed1), labelHello, 96, 200);
  gtk_widget_set_size_request (labelHello, 104, 32);

  g_signal_connect ((gpointer) buttonHello, "clicked",
                    G_CALLBACK (on_buttonHello_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (myWindow, myWindow, "myWindow");
  GLADE_HOOKUP_OBJECT (myWindow, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (myWindow, entryNom, "entryNom");
  GLADE_HOOKUP_OBJECT (myWindow, labelNom, "labelNom");
  GLADE_HOOKUP_OBJECT (myWindow, buttonHello, "buttonHello");
  GLADE_HOOKUP_OBJECT (myWindow, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (myWindow, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (myWindow, image1, "image1");
  GLADE_HOOKUP_OBJECT (myWindow, label2, "label2");
  GLADE_HOOKUP_OBJECT (myWindow, labelHello, "labelHello");

  return myWindow;
}

