/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_window1 (void);
GtkWidget* create_window_hotels (void);
GtkWidget* create_window_offre_of_the_days (void);
GtkWidget* create_window_name_of_leasing (void);
