/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window1 (void)
{
  GtkWidget *window1;
  GtkWidget *fixed1;
  GtkWidget *usernametext;
  GtkWidget *passwordtext;
  GtkWidget *error;
  GtkWidget *username;
  GtkWidget *password;
  GtkWidget *label2;
  GtkWidget *label3;
  GtkWidget *usernameajouter;
  GtkWidget *passwordajouter;
  GtkWidget *label6;
  GtkWidget *label5;
  GtkWidget *roleajouter;
  GtkWidget *label7;
  GtkWidget *affichertext;
  GtkWidget *afficher;
  GtkWidget *Login;
  GtkWidget *label4;
  GtkWidget *ajouter;

  window1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window1), _("window1"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (window1), fixed1);

  usernametext = gtk_entry_new ();
  gtk_widget_show (usernametext);
  gtk_fixed_put (GTK_FIXED (fixed1), usernametext, 136, 64);
  gtk_widget_set_size_request (usernametext, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (usernametext), 8226);

  passwordtext = gtk_entry_new ();
  gtk_widget_show (passwordtext);
  gtk_fixed_put (GTK_FIXED (fixed1), passwordtext, 136, 128);
  gtk_widget_set_size_request (passwordtext, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (passwordtext), 8226);

  error = gtk_label_new ("");
  gtk_widget_show (error);
  gtk_fixed_put (GTK_FIXED (fixed1), error, 80, 176);
  gtk_widget_set_size_request (error, 280, 40);

  username = gtk_label_new (_("username:"));
  gtk_widget_show (username);
  gtk_fixed_put (GTK_FIXED (fixed1), username, 40, 64);
  gtk_widget_set_size_request (username, 96, 32);

  password = gtk_label_new (_("password:"));
  gtk_widget_show (password);
  gtk_fixed_put (GTK_FIXED (fixed1), password, 48, 128);
  gtk_widget_set_size_request (password, 88, 24);

  label2 = gtk_label_new (_("zone fnct verifier"));
  gtk_widget_show (label2);
  gtk_fixed_put (GTK_FIXED (fixed1), label2, 88, 16);
  gtk_widget_set_size_request (label2, 137, 24);

  label3 = gtk_label_new (_("zone fnct afficher"));
  gtk_widget_show (label3);
  gtk_fixed_put (GTK_FIXED (fixed1), label3, 360, 16);
  gtk_widget_set_size_request (label3, 153, 16);

  usernameajouter = gtk_entry_new ();
  gtk_widget_show (usernameajouter);
  gtk_fixed_put (GTK_FIXED (fixed1), usernameajouter, 672, 64);
  gtk_widget_set_size_request (usernameajouter, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (usernameajouter), 8226);

  passwordajouter = gtk_entry_new ();
  gtk_widget_show (passwordajouter);
  gtk_fixed_put (GTK_FIXED (fixed1), passwordajouter, 672, 120);
  gtk_widget_set_size_request (passwordajouter, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (passwordajouter), 8226);

  label6 = gtk_label_new (_("password"));
  gtk_widget_show (label6);
  gtk_fixed_put (GTK_FIXED (fixed1), label6, 584, 128);
  gtk_widget_set_size_request (label6, 80, 16);

  label5 = gtk_label_new (_("username"));
  gtk_widget_show (label5);
  gtk_fixed_put (GTK_FIXED (fixed1), label5, 584, 72);
  gtk_widget_set_size_request (label5, 81, 16);

  roleajouter = gtk_entry_new ();
  gtk_widget_show (roleajouter);
  gtk_fixed_put (GTK_FIXED (fixed1), roleajouter, 672, 176);
  gtk_widget_set_size_request (roleajouter, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (roleajouter), 8226);

  label7 = gtk_label_new (_("role"));
  gtk_widget_show (label7);
  gtk_fixed_put (GTK_FIXED (fixed1), label7, 616, 184);
  gtk_widget_set_size_request (label7, 41, 17);

  affichertext = gtk_label_new ("");
  gtk_widget_show (affichertext);
  gtk_fixed_put (GTK_FIXED (fixed1), affichertext, 328, 40);
  gtk_widget_set_size_request (affichertext, 240, 184);

  afficher = gtk_button_new_with_mnemonic (_("afficher tt les users"));
  gtk_widget_show (afficher);
  gtk_fixed_put (GTK_FIXED (fixed1), afficher, 360, 240);
  gtk_widget_set_size_request (afficher, 172, 40);

  Login = gtk_button_new_with_mnemonic (_("Login"));
  gtk_widget_show (Login);
  gtk_fixed_put (GTK_FIXED (fixed1), Login, 136, 200);
  gtk_widget_set_size_request (Login, 68, 29);

  label4 = gtk_label_new (_("zone fnct ajouter"));
  gtk_widget_show (label4);
  gtk_fixed_put (GTK_FIXED (fixed1), label4, 704, 16);
  gtk_widget_set_size_request (label4, 113, 16);

  ajouter = gtk_button_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (ajouter);
  gtk_fixed_put (GTK_FIXED (fixed1), ajouter, 720, 216);
  gtk_widget_set_size_request (ajouter, 68, 29);

  g_signal_connect ((gpointer) afficher, "clicked",
                    G_CALLBACK (on_afficher_clicked),
                    NULL);
  g_signal_connect ((gpointer) Login, "clicked",
                    G_CALLBACK (on_Login_clicked),
                    NULL);
  g_signal_connect ((gpointer) ajouter, "clicked",
                    G_CALLBACK (on_ajouter_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window1, window1, "window1");
  GLADE_HOOKUP_OBJECT (window1, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (window1, usernametext, "usernametext");
  GLADE_HOOKUP_OBJECT (window1, passwordtext, "passwordtext");
  GLADE_HOOKUP_OBJECT (window1, error, "error");
  GLADE_HOOKUP_OBJECT (window1, username, "username");
  GLADE_HOOKUP_OBJECT (window1, password, "password");
  GLADE_HOOKUP_OBJECT (window1, label2, "label2");
  GLADE_HOOKUP_OBJECT (window1, label3, "label3");
  GLADE_HOOKUP_OBJECT (window1, usernameajouter, "usernameajouter");
  GLADE_HOOKUP_OBJECT (window1, passwordajouter, "passwordajouter");
  GLADE_HOOKUP_OBJECT (window1, label6, "label6");
  GLADE_HOOKUP_OBJECT (window1, label5, "label5");
  GLADE_HOOKUP_OBJECT (window1, roleajouter, "roleajouter");
  GLADE_HOOKUP_OBJECT (window1, label7, "label7");
  GLADE_HOOKUP_OBJECT (window1, affichertext, "affichertext");
  GLADE_HOOKUP_OBJECT (window1, afficher, "afficher");
  GLADE_HOOKUP_OBJECT (window1, Login, "Login");
  GLADE_HOOKUP_OBJECT (window1, label4, "label4");
  GLADE_HOOKUP_OBJECT (window1, ajouter, "ajouter");

  return window1;
}

GtkWidget*
create_window2 (void)
{
  GtkWidget *window2;
  GtkWidget *fixed2;
  GtkWidget *label1;

  window2 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window2), _("window2"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (window2), fixed2);

  label1 = gtk_label_new (_("Welcome"));
  gtk_widget_show (label1);
  gtk_fixed_put (GTK_FIXED (fixed2), label1, 136, 112);
  gtk_widget_set_size_request (label1, 120, 48);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window2, window2, "window2");
  GLADE_HOOKUP_OBJECT (window2, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (window2, label1, "label1");

  return window2;
}

