/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_EspaceAdminHome (void);
GtkWidget* create_EspaceAdminClaims (void);
GtkWidget* create_EspaceAdminClaimsAnswer (void);
GtkWidget* create_EspaceAdminStatistical (void);
GtkWidget* create_EspaceAdminAddmemberInfo (void);
GtkWidget* create_EspaceAdminDeletemembersInfo (void);
GtkWidget* create_windowuploadcv (void);
