/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window1 (void)
{
  GtkWidget *window1;
  GtkWidget *fixed1;
  GtkObject *jour_adj;
  GtkWidget *jour;
  GtkObject *mois_adj;
  GtkWidget *mois;
  GtkObject *ann__e_adj;
  GtkWidget *ann__e;
  GtkWidget *combobox1;
  GtkWidget *combobox2;
  GtkWidget *combobox3;
  GtkWidget *labeldatereservation;
  GtkWidget *labeljour;
  GtkWidget *labelmois;
  GtkWidget *labelannee;
  GtkWidget *labelheurereservation;
  GtkWidget *labelbloc;
  GtkWidget *labelsalle;
  GtkWidget *buttonvalider;
  GtkWidget *buttonconfirmer;

  window1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window1), _("window1"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (window1), fixed1);

  jour_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  jour = gtk_spin_button_new (GTK_ADJUSTMENT (jour_adj), 1, 0);
  gtk_widget_show (jour);
  gtk_fixed_put (GTK_FIXED (fixed1), jour, 248, 96);
  gtk_widget_set_size_request (jour, 60, 27);

  mois_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  mois = gtk_spin_button_new (GTK_ADJUSTMENT (mois_adj), 1, 0);
  gtk_widget_show (mois);
  gtk_fixed_put (GTK_FIXED (fixed1), mois, 376, 96);
  gtk_widget_set_size_request (mois, 60, 27);

  ann__e_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  ann__e = gtk_spin_button_new (GTK_ADJUSTMENT (ann__e_adj), 1, 0);
  gtk_widget_show (ann__e);
  gtk_fixed_put (GTK_FIXED (fixed1), ann__e, 520, 96);
  gtk_widget_set_size_request (ann__e, 80, 27);

  combobox1 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox1);
  gtk_fixed_put (GTK_FIXED (fixed1), combobox1, 224, 176);
  gtk_widget_set_size_request (combobox1, 232, 40);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("9h==>12:15h"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("14h==>17:15h"));

  combobox2 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox2);
  gtk_fixed_put (GTK_FIXED (fixed1), combobox2, 224, 240);
  gtk_widget_set_size_request (combobox2, 232, 39);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("A"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("B"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("C"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("D"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("E"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("H"));

  combobox3 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox3);
  gtk_fixed_put (GTK_FIXED (fixed1), combobox3, 224, 408);
  gtk_widget_set_size_request (combobox3, 240, 40);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3), _(" "));

  labeldatereservation = gtk_label_new (_("date de reservation :"));
  gtk_widget_show (labeldatereservation);
  gtk_fixed_put (GTK_FIXED (fixed1), labeldatereservation, 24, 96);
  gtk_widget_set_size_request (labeldatereservation, 192, 25);

  labeljour = gtk_label_new (_("jour"));
  gtk_widget_show (labeljour);
  gtk_fixed_put (GTK_FIXED (fixed1), labeljour, 192, 96);
  gtk_widget_set_size_request (labeljour, 64, 25);

  labelmois = gtk_label_new (_("mois"));
  gtk_widget_show (labelmois);
  gtk_fixed_put (GTK_FIXED (fixed1), labelmois, 312, 96);
  gtk_widget_set_size_request (labelmois, 64, 25);

  labelannee = gtk_label_new (_("ann\303\251e"));
  gtk_widget_show (labelannee);
  gtk_fixed_put (GTK_FIXED (fixed1), labelannee, 440, 96);
  gtk_widget_set_size_request (labelannee, 96, 33);

  labelheurereservation = gtk_label_new (_("Heure de reservation :"));
  gtk_widget_show (labelheurereservation);
  gtk_fixed_put (GTK_FIXED (fixed1), labelheurereservation, 32, 176);
  gtk_widget_set_size_request (labelheurereservation, 176, 33);

  labelbloc = gtk_label_new (_("Bloc :"));
  gtk_widget_show (labelbloc);
  gtk_fixed_put (GTK_FIXED (fixed1), labelbloc, 40, 248);
  gtk_widget_set_size_request (labelbloc, 128, 25);

  labelsalle = gtk_label_new (_("choisir une salle :"));
  gtk_widget_show (labelsalle);
  gtk_fixed_put (GTK_FIXED (fixed1), labelsalle, 0, 408);
  gtk_widget_set_size_request (labelsalle, 216, 41);

  buttonvalider = gtk_button_new_with_mnemonic (_("valider"));
  gtk_widget_show (buttonvalider);
  gtk_fixed_put (GTK_FIXED (fixed1), buttonvalider, 248, 320);
  gtk_widget_set_size_request (buttonvalider, 184, 45);

  buttonconfirmer = gtk_button_new_with_mnemonic (_("confirmer"));
  gtk_widget_show (buttonconfirmer);
  gtk_fixed_put (GTK_FIXED (fixed1), buttonconfirmer, 488, 488);
  gtk_widget_set_size_request (buttonconfirmer, 176, 40);

  g_signal_connect ((gpointer) buttonvalider, "clicked",
                    G_CALLBACK (on_buttonvalider_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonconfirmer, "clicked",
                    G_CALLBACK (on_buttonconfirmer_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window1, window1, "window1");
  GLADE_HOOKUP_OBJECT (window1, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (window1, jour, "jour");
  GLADE_HOOKUP_OBJECT (window1, mois, "mois");
  GLADE_HOOKUP_OBJECT (window1, ann__e, "ann__e");
  GLADE_HOOKUP_OBJECT (window1, combobox1, "combobox1");
  GLADE_HOOKUP_OBJECT (window1, combobox2, "combobox2");
  GLADE_HOOKUP_OBJECT (window1, combobox3, "combobox3");
  GLADE_HOOKUP_OBJECT (window1, labeldatereservation, "labeldatereservation");
  GLADE_HOOKUP_OBJECT (window1, labeljour, "labeljour");
  GLADE_HOOKUP_OBJECT (window1, labelmois, "labelmois");
  GLADE_HOOKUP_OBJECT (window1, labelannee, "labelannee");
  GLADE_HOOKUP_OBJECT (window1, labelheurereservation, "labelheurereservation");
  GLADE_HOOKUP_OBJECT (window1, labelbloc, "labelbloc");
  GLADE_HOOKUP_OBJECT (window1, labelsalle, "labelsalle");
  GLADE_HOOKUP_OBJECT (window1, buttonvalider, "buttonvalider");
  GLADE_HOOKUP_OBJECT (window1, buttonconfirmer, "buttonconfirmer");

  return window1;
}

