/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_mywindow (void);
GtkWidget* create_window1 (void);
GtkWidget* create_settings (void);
GtkWidget* create_setting (void);
GtkWidget* create_Settings (void);
GtkWidget* create_window5 (void);
GtkWidget* create_sending_code (void);
GtkWidget* create_checking_customers_demands (void);
GtkWidget* create_customer1 (void);
