/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_mywindow (void)
{
  GtkWidget *mywindow;
  GtkWidget *fixed1;
  GtkWidget *labelnom;
  GtkWidget *entrynom;
  GtkWidget *comboboxentry1;
  GtkWidget *labelhello;
  GtkWidget *buttonhello;

  mywindow = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (mywindow), _("myfirstexemple"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (mywindow), fixed1);

  labelnom = gtk_label_new (_("votre nom"));
  gtk_widget_show (labelnom);
  gtk_fixed_put (GTK_FIXED (fixed1), labelnom, 56, 48);
  gtk_widget_set_size_request (labelnom, 112, 16);

  entrynom = gtk_entry_new ();
  gtk_widget_show (entrynom);
  gtk_fixed_put (GTK_FIXED (fixed1), entrynom, 160, 40);
  gtk_widget_set_size_request (entrynom, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrynom), 8226);

  comboboxentry1 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry1);
  gtk_fixed_put (GTK_FIXED (fixed1), comboboxentry1, 104, 96);
  gtk_widget_set_size_request (comboboxentry1, 189, 29);

  labelhello = gtk_label_new (_("hello"));
  gtk_widget_show (labelhello);
  gtk_fixed_put (GTK_FIXED (fixed1), labelhello, 144, 192);
  gtk_widget_set_size_request (labelhello, 41, 17);

  buttonhello = gtk_button_new_with_mnemonic (_("hello"));
  gtk_widget_show (buttonhello);
  gtk_fixed_put (GTK_FIXED (fixed1), buttonhello, 136, 144);
  gtk_widget_set_size_request (buttonhello, 68, 29);

  g_signal_connect ((gpointer) buttonhello, "clicked",
                    G_CALLBACK (on_buttonhello_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonhello, "clicked",
                    G_CALLBACK (on_buttonhello_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonhello, "clicked",
                    G_CALLBACK (on_buttonhello_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (mywindow, mywindow, "mywindow");
  GLADE_HOOKUP_OBJECT (mywindow, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (mywindow, labelnom, "labelnom");
  GLADE_HOOKUP_OBJECT (mywindow, entrynom, "entrynom");
  GLADE_HOOKUP_OBJECT (mywindow, comboboxentry1, "comboboxentry1");
  GLADE_HOOKUP_OBJECT (mywindow, labelhello, "labelhello");
  GLADE_HOOKUP_OBJECT (mywindow, buttonhello, "buttonhello");

  return mywindow;
}

GtkWidget*
create_window1 (void)
{
  GtkWidget *window1;

  window1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window1), _("window1"));

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window1, window1, "window1");

  return window1;
}

GtkWidget*
create_settings (void)
{
  GtkWidget *settings;
  GtkWidget *button1;

  settings = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (settings), _("settings"));

  button1 = gtk_button_new_with_mnemonic (_("button1"));
  gtk_widget_show (button1);
  gtk_container_add (GTK_CONTAINER (settings), button1);
  gtk_container_set_border_width (GTK_CONTAINER (button1), 2);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (settings, settings, "settings");
  GLADE_HOOKUP_OBJECT (settings, button1, "button1");

  return settings;
}

GtkWidget*
create_setting (void)
{
  GtkWidget *setting;
  GtkWidget *button2;

  setting = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (setting), _("settings"));

  button2 = gtk_button_new_with_mnemonic (_("button2"));
  gtk_widget_show (button2);
  gtk_container_add (GTK_CONTAINER (setting), button2);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (setting, setting, "setting");
  GLADE_HOOKUP_OBJECT (setting, button2, "button2");

  return setting;
}

GtkWidget*
create_Settings (void)
{
  GtkWidget *Settings;
  GtkWidget *togglebutton1;

  Settings = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Settings), _("Settings"));

  togglebutton1 = gtk_toggle_button_new_with_mnemonic (_("togglebutton1"));
  gtk_widget_show (togglebutton1);
  gtk_container_add (GTK_CONTAINER (Settings), togglebutton1);
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (togglebutton1), TRUE);
  gtk_toggle_button_set_inconsistent (GTK_TOGGLE_BUTTON (togglebutton1), TRUE);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Settings, Settings, "Settings");
  GLADE_HOOKUP_OBJECT (Settings, togglebutton1, "togglebutton1");

  return Settings;
}

GtkWidget*
create_window5 (void)
{
  GtkWidget *window5;
  GtkWidget *label1;

  window5 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window5), _("window5"));

  label1 = gtk_label_new (_("label1"));
  gtk_widget_show (label1);
  gtk_container_add (GTK_CONTAINER (window5), label1);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window5, window5, "window5");
  GLADE_HOOKUP_OBJECT (window5, label1, "label1");

  return window5;
}

GtkWidget*
create_sending_code (void)
{
  GtkWidget *sending_code;
  GtkWidget *fixed2;
  GtkWidget *button3;
  GtkWidget *checkbutton4;
  GtkWidget *checkbutton2;
  GtkWidget *checkbutton3;
  GtkWidget *checkbutton1;
  GtkWidget *button7;
  GtkWidget *button6;
  GtkWidget *button4;
  GtkWidget *button5;
  GtkWidget *button8;
  GtkWidget *checkbutton5;

  sending_code = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (sending_code), _("sending code"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (sending_code), fixed2);
  gtk_container_set_border_width (GTK_CONTAINER (fixed2), 4);

  button3 = gtk_button_new_with_mnemonic (_("log out"));
  gtk_widget_show (button3);
  gtk_fixed_put (GTK_FIXED (fixed2), button3, 24, 24);
  gtk_widget_set_size_request (button3, 68, 29);

  checkbutton4 = gtk_check_button_new_with_mnemonic ("");
  gtk_widget_show (checkbutton4);
  gtk_fixed_put (GTK_FIXED (fixed2), checkbutton4, 280, 200);
  gtk_widget_set_size_request (checkbutton4, 24, 24);

  checkbutton2 = gtk_check_button_new_with_mnemonic ("");
  gtk_widget_show (checkbutton2);
  gtk_fixed_put (GTK_FIXED (fixed2), checkbutton2, 280, 128);
  gtk_widget_set_size_request (checkbutton2, 24, 24);

  checkbutton3 = gtk_check_button_new_with_mnemonic ("");
  gtk_widget_show (checkbutton3);
  gtk_fixed_put (GTK_FIXED (fixed2), checkbutton3, 280, 168);
  gtk_widget_set_size_request (checkbutton3, 24, 24);

  checkbutton1 = gtk_check_button_new_with_mnemonic ("");
  gtk_widget_show (checkbutton1);
  gtk_fixed_put (GTK_FIXED (fixed2), checkbutton1, 280, 88);
  gtk_widget_set_size_request (checkbutton1, 24, 32);

  button7 = gtk_button_new_with_mnemonic (_("send code"));
  gtk_widget_show (button7);
  gtk_fixed_put (GTK_FIXED (fixed2), button7, 304, 200);
  gtk_widget_set_size_request (button7, 88, 24);

  button6 = gtk_button_new_with_mnemonic (_("send code"));
  gtk_widget_show (button6);
  gtk_fixed_put (GTK_FIXED (fixed2), button6, 304, 168);
  gtk_widget_set_size_request (button6, 88, 24);

  button4 = gtk_button_new_with_mnemonic (_("send code"));
  gtk_widget_show (button4);
  gtk_fixed_put (GTK_FIXED (fixed2), button4, 304, 96);
  gtk_widget_set_size_request (button4, 88, 24);

  button5 = gtk_button_new_with_mnemonic (_("send code"));
  gtk_widget_show (button5);
  gtk_fixed_put (GTK_FIXED (fixed2), button5, 304, 128);
  gtk_widget_set_size_request (button5, 88, 24);

  button8 = gtk_button_new_with_mnemonic (_("send code"));
  gtk_widget_show (button8);
  gtk_fixed_put (GTK_FIXED (fixed2), button8, 304, 232);
  gtk_widget_set_size_request (button8, 88, 24);

  checkbutton5 = gtk_check_button_new_with_mnemonic ("");
  gtk_widget_show (checkbutton5);
  gtk_fixed_put (GTK_FIXED (fixed2), checkbutton5, 280, 232);
  gtk_widget_set_size_request (checkbutton5, 24, 24);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (sending_code, sending_code, "sending_code");
  GLADE_HOOKUP_OBJECT (sending_code, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (sending_code, button3, "button3");
  GLADE_HOOKUP_OBJECT (sending_code, checkbutton4, "checkbutton4");
  GLADE_HOOKUP_OBJECT (sending_code, checkbutton2, "checkbutton2");
  GLADE_HOOKUP_OBJECT (sending_code, checkbutton3, "checkbutton3");
  GLADE_HOOKUP_OBJECT (sending_code, checkbutton1, "checkbutton1");
  GLADE_HOOKUP_OBJECT (sending_code, button7, "button7");
  GLADE_HOOKUP_OBJECT (sending_code, button6, "button6");
  GLADE_HOOKUP_OBJECT (sending_code, button4, "button4");
  GLADE_HOOKUP_OBJECT (sending_code, button5, "button5");
  GLADE_HOOKUP_OBJECT (sending_code, button8, "button8");
  GLADE_HOOKUP_OBJECT (sending_code, checkbutton5, "checkbutton5");

  return sending_code;
}

GtkWidget*
create_checking_customers_demands (void)
{
  GtkWidget *checking_customers_demands;
  GtkWidget *fixed3;
  GtkWidget *button9;
  GtkWidget *hbuttonbox1;
  GtkWidget *button13;
  GtkWidget *button11;
  GtkWidget *button12;

  checking_customers_demands = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (checking_customers_demands), _("check customers demands"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (checking_customers_demands), fixed3);

  button9 = gtk_button_new_with_mnemonic (_("log in"));
  gtk_widget_show (button9);
  gtk_fixed_put (GTK_FIXED (fixed3), button9, 24, 24);
  gtk_widget_set_size_request (button9, 68, 29);

  hbuttonbox1 = gtk_hbutton_box_new ();
  gtk_widget_show (hbuttonbox1);
  gtk_fixed_put (GTK_FIXED (fixed3), hbuttonbox1, 80, 120);
  gtk_widget_set_size_request (hbuttonbox1, 170, 29);

  button13 = gtk_button_new_with_mnemonic (_("customer1"));
  gtk_widget_show (button13);
  gtk_fixed_put (GTK_FIXED (fixed3), button13, 144, 88);
  gtk_widget_set_size_request (button13, 104, 32);

  button11 = gtk_button_new_with_mnemonic (_("customer2"));
  gtk_widget_show (button11);
  gtk_fixed_put (GTK_FIXED (fixed3), button11, 144, 136);
  gtk_widget_set_size_request (button11, 104, 32);

  button12 = gtk_button_new_with_mnemonic (_("customer3"));
  gtk_widget_show (button12);
  gtk_fixed_put (GTK_FIXED (fixed3), button12, 144, 184);
  gtk_widget_set_size_request (button12, 104, 32);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (checking_customers_demands, checking_customers_demands, "checking_customers_demands");
  GLADE_HOOKUP_OBJECT (checking_customers_demands, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (checking_customers_demands, button9, "button9");
  GLADE_HOOKUP_OBJECT (checking_customers_demands, hbuttonbox1, "hbuttonbox1");
  GLADE_HOOKUP_OBJECT (checking_customers_demands, button13, "button13");
  GLADE_HOOKUP_OBJECT (checking_customers_demands, button11, "button11");
  GLADE_HOOKUP_OBJECT (checking_customers_demands, button12, "button12");

  return checking_customers_demands;
}

GtkWidget*
create_customer1 (void)
{
  GtkWidget *customer1;
  GtkWidget *fixed4;
  GtkWidget *button14;
  GtkWidget *textview1;
  GtkWidget *button15;
  GtkWidget *button16;

  customer1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (customer1), _("customer1"));

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (customer1), fixed4);

  button14 = gtk_button_new_with_mnemonic (_("log out"));
  gtk_widget_show (button14);
  gtk_fixed_put (GTK_FIXED (fixed4), button14, 24, 24);
  gtk_widget_set_size_request (button14, 76, 29);

  textview1 = gtk_text_view_new ();
  gtk_widget_show (textview1);
  gtk_fixed_put (GTK_FIXED (fixed4), textview1, 128, 88);
  gtk_widget_set_size_request (textview1, 144, 96);
  gtk_text_view_set_justification (GTK_TEXT_VIEW (textview1), GTK_JUSTIFY_CENTER);
  gtk_text_buffer_set_text (gtk_text_view_get_buffer (GTK_TEXT_VIEW (textview1)), _("Demands content"), -1);

  button15 = gtk_button_new_with_mnemonic (_("accept"));
  gtk_widget_show (button15);
  gtk_fixed_put (GTK_FIXED (fixed4), button15, 88, 208);
  gtk_widget_set_size_request (button15, 76, 29);

  button16 = gtk_button_new_with_mnemonic (_("refuse"));
  gtk_widget_show (button16);
  gtk_fixed_put (GTK_FIXED (fixed4), button16, 240, 208);
  gtk_widget_set_size_request (button16, 76, 29);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (customer1, customer1, "customer1");
  GLADE_HOOKUP_OBJECT (customer1, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (customer1, button14, "button14");
  GLADE_HOOKUP_OBJECT (customer1, textview1, "textview1");
  GLADE_HOOKUP_OBJECT (customer1, button15, "button15");
  GLADE_HOOKUP_OBJECT (customer1, button16, "button16");

  return customer1;
}

