/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_EspaceAdminHome (void)
{
  GtkWidget *EspaceAdminHome;
  GtkWidget *fixedHome;
  GtkWidget *hseparator1;
  GtkWidget *vseparator1;
  GtkWidget *label2;
  GtkWidget *labelDashboard;
  GtkWidget *Logout;
  GtkWidget *Home;
  GtkWidget *Claims;
  GtkWidget *PromotionalCode;
  GtkWidget *Statistical;
  GtkWidget *AddMembers;
  GtkWidget *DeleteMembers;
  GtkWidget *Settings;
  GtkWidget *HomeAgentsNumber;
  GtkWidget *HomeCustomersNumber;
  GtkWidget *label93;
  GtkWidget *labelAdminsnumber;
  GtkWidget *HomeAdminsNumber;
  GtkWidget *labelCustomernumber;
  GtkWidget *labelAgentsnumber;
  GtkWidget *label94;
  GtkWidget *HomeTotalNumber;
  GtkWidget *label96;
  GtkWidget *label100;
  GtkWidget *label102;
  GtkWidget *label104;
  GtkWidget *HomePasswordShow;
  GtkWidget *HomePhoneNumber;
  GtkWidget *HomeBirthDate;
  GtkWidget *label98;
  GtkWidget *HomeEmail;
  GtkWidget *HomePassword;
  GtkWidget *HomeConnectedAs;

  EspaceAdminHome = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (EspaceAdminHome), _("Tunivist"));
  gtk_window_set_position (GTK_WINDOW (EspaceAdminHome), GTK_WIN_POS_CENTER);

  fixedHome = gtk_fixed_new ();
  gtk_widget_show (fixedHome);
  gtk_container_add (GTK_CONTAINER (EspaceAdminHome), fixedHome);

  hseparator1 = gtk_hseparator_new ();
  gtk_widget_show (hseparator1);
  gtk_fixed_put (GTK_FIXED (fixedHome), hseparator1, 0, 72);
  gtk_widget_set_size_request (hseparator1, 1168, 16);

  vseparator1 = gtk_vseparator_new ();
  gtk_widget_show (vseparator1);
  gtk_fixed_put (GTK_FIXED (fixedHome), vseparator1, 232, 80);
  gtk_widget_set_size_request (vseparator1, 16, 448);

  label2 = gtk_label_new (_("Welcome Boss"));
  gtk_widget_show (label2);
  gtk_fixed_put (GTK_FIXED (fixedHome), label2, 472, 8);
  gtk_widget_set_size_request (label2, 368, 40);
  gtk_misc_set_alignment (GTK_MISC (label2), 0.5, 0.49);

  labelDashboard = gtk_label_new (_("Dashboard"));
  gtk_widget_show (labelDashboard);
  gtk_fixed_put (GTK_FIXED (fixedHome), labelDashboard, 56, 88);
  gtk_widget_set_size_request (labelDashboard, 120, 40);
  gtk_misc_set_alignment (GTK_MISC (labelDashboard), 0.49, 0.5);

  Logout = gtk_button_new_with_mnemonic (_("Logout"));
  gtk_widget_show (Logout);
  gtk_fixed_put (GTK_FIXED (fixedHome), Logout, 32, 16);
  gtk_widget_set_size_request (Logout, 68, 29);

  Home = gtk_button_new_with_mnemonic (_("Home"));
  gtk_widget_show (Home);
  gtk_fixed_put (GTK_FIXED (fixedHome), Home, 40, 136);
  gtk_widget_set_size_request (Home, 144, 40);

  Claims = gtk_button_new_with_mnemonic (_("Claims"));
  gtk_widget_show (Claims);
  gtk_fixed_put (GTK_FIXED (fixedHome), Claims, 40, 200);
  gtk_widget_set_size_request (Claims, 144, 32);

  PromotionalCode = gtk_button_new_with_mnemonic (_("Promotional code"));
  gtk_widget_show (PromotionalCode);
  gtk_fixed_put (GTK_FIXED (fixedHome), PromotionalCode, 40, 248);
  gtk_widget_set_size_request (PromotionalCode, 144, 37);

  Statistical = gtk_button_new_with_mnemonic (_("Statistical"));
  gtk_widget_show (Statistical);
  gtk_fixed_put (GTK_FIXED (fixedHome), Statistical, 40, 304);
  gtk_widget_set_size_request (Statistical, 144, 32);

  AddMembers = gtk_button_new_with_mnemonic (_("Add members"));
  gtk_widget_show (AddMembers);
  gtk_fixed_put (GTK_FIXED (fixedHome), AddMembers, 40, 360);
  gtk_widget_set_size_request (AddMembers, 144, 32);

  DeleteMembers = gtk_button_new_with_mnemonic (_("Delete members"));
  gtk_widget_show (DeleteMembers);
  gtk_fixed_put (GTK_FIXED (fixedHome), DeleteMembers, 40, 416);
  gtk_widget_set_size_request (DeleteMembers, 144, 32);

  Settings = gtk_button_new_with_mnemonic (_("Settings"));
  gtk_widget_show (Settings);
  gtk_fixed_put (GTK_FIXED (fixedHome), Settings, 40, 472);
  gtk_widget_set_size_request (Settings, 144, 32);

  HomeAgentsNumber = gtk_label_new (_("0"));
  gtk_widget_show (HomeAgentsNumber);
  gtk_fixed_put (GTK_FIXED (fixedHome), HomeAgentsNumber, 952, 240);
  gtk_widget_set_size_request (HomeAgentsNumber, 128, 40);

  HomeCustomersNumber = gtk_label_new (_("0"));
  gtk_widget_show (HomeCustomersNumber);
  gtk_fixed_put (GTK_FIXED (fixedHome), HomeCustomersNumber, 952, 168);
  gtk_widget_set_size_request (HomeCustomersNumber, 128, 40);

  label93 = gtk_label_new (_("General Info"));
  gtk_widget_show (label93);
  gtk_fixed_put (GTK_FIXED (fixedHome), label93, 920, 120);
  gtk_widget_set_size_request (label93, 129, 24);

  labelAdminsnumber = gtk_label_new (_("Admins number"));
  gtk_widget_show (labelAdminsnumber);
  gtk_fixed_put (GTK_FIXED (fixedHome), labelAdminsnumber, 848, 320);
  gtk_widget_set_size_request (labelAdminsnumber, 129, 32);

  HomeAdminsNumber = gtk_label_new (_("0"));
  gtk_widget_show (HomeAdminsNumber);
  gtk_fixed_put (GTK_FIXED (fixedHome), HomeAdminsNumber, 952, 312);
  gtk_widget_set_size_request (HomeAdminsNumber, 128, 40);

  labelCustomernumber = gtk_label_new (_("Customers number"));
  gtk_widget_show (labelCustomernumber);
  gtk_fixed_put (GTK_FIXED (fixedHome), labelCustomernumber, 816, 176);
  gtk_widget_set_size_request (labelCustomernumber, 176, 32);

  labelAgentsnumber = gtk_label_new (_("Agents number"));
  gtk_widget_show (labelAgentsnumber);
  gtk_fixed_put (GTK_FIXED (fixedHome), labelAgentsnumber, 840, 248);
  gtk_widget_set_size_request (labelAgentsnumber, 152, 32);

  label94 = gtk_label_new (_("Total users"));
  gtk_widget_show (label94);
  gtk_fixed_put (GTK_FIXED (fixedHome), label94, 864, 408);
  gtk_widget_set_size_request (label94, 129, 48);

  HomeTotalNumber = gtk_label_new (_("0"));
  gtk_widget_show (HomeTotalNumber);
  gtk_fixed_put (GTK_FIXED (fixedHome), HomeTotalNumber, 976, 408);
  gtk_widget_set_size_request (HomeTotalNumber, 81, 40);

  label96 = gtk_label_new (_("Connected as:"));
  gtk_widget_show (label96);
  gtk_fixed_put (GTK_FIXED (fixedHome), label96, 288, 168);
  gtk_widget_set_size_request (label96, 112, 16);

  label100 = gtk_label_new (_("Phone number:"));
  gtk_widget_show (label100);
  gtk_fixed_put (GTK_FIXED (fixedHome), label100, 272, 264);
  gtk_widget_set_size_request (label100, 121, 16);

  label102 = gtk_label_new (_("Birth date:"));
  gtk_widget_show (label102);
  gtk_fixed_put (GTK_FIXED (fixedHome), label102, 296, 312);
  gtk_widget_set_size_request (label102, 105, 16);

  label104 = gtk_label_new (_("Password:"));
  gtk_widget_show (label104);
  gtk_fixed_put (GTK_FIXED (fixedHome), label104, 296, 368);
  gtk_widget_set_size_request (label104, 105, 16);

  HomePasswordShow = gtk_button_new_with_mnemonic (_("Show"));
  gtk_widget_show (HomePasswordShow);
  gtk_fixed_put (GTK_FIXED (fixedHome), HomePasswordShow, 560, 360);
  gtk_widget_set_size_request (HomePasswordShow, 56, 32);

  HomePhoneNumber = gtk_label_new (_("*"));
  gtk_widget_show (HomePhoneNumber);
  gtk_fixed_put (GTK_FIXED (fixedHome), HomePhoneNumber, 416, 264);
  gtk_widget_set_size_request (HomePhoneNumber, 168, 16);

  HomeBirthDate = gtk_label_new (_("*"));
  gtk_widget_show (HomeBirthDate);
  gtk_fixed_put (GTK_FIXED (fixedHome), HomeBirthDate, 424, 312);
  gtk_widget_set_size_request (HomeBirthDate, 152, 16);

  label98 = gtk_label_new (_("Email:"));
  gtk_widget_show (label98);
  gtk_fixed_put (GTK_FIXED (fixedHome), label98, 336, 216);
  gtk_widget_set_size_request (label98, 65, 16);

  HomeEmail = gtk_label_new (_("*"));
  gtk_widget_show (HomeEmail);
  gtk_fixed_put (GTK_FIXED (fixedHome), HomeEmail, 392, 216);
  gtk_widget_set_size_request (HomeEmail, 224, 16);

  HomePassword = gtk_label_new (_("********"));
  gtk_widget_show (HomePassword);
  gtk_fixed_put (GTK_FIXED (fixedHome), HomePassword, 392, 368);
  gtk_widget_set_size_request (HomePassword, 168, 16);

  HomeConnectedAs = gtk_label_new (_("*"));
  gtk_widget_show (HomeConnectedAs);
  gtk_fixed_put (GTK_FIXED (fixedHome), HomeConnectedAs, 400, 168);
  gtk_widget_set_size_request (HomeConnectedAs, 200, 16);

  g_signal_connect ((gpointer) EspaceAdminHome, "show",
                    G_CALLBACK (on_EspaceAdminHome_show),
                    NULL);
  g_signal_connect ((gpointer) Logout, "clicked",
                    G_CALLBACK (on_Logout_clicked),
                    NULL);
  g_signal_connect ((gpointer) Home, "clicked",
                    G_CALLBACK (on_Home_clicked),
                    NULL);
  g_signal_connect ((gpointer) Claims, "clicked",
                    G_CALLBACK (on_Claims_clicked),
                    NULL);
  g_signal_connect ((gpointer) PromotionalCode, "clicked",
                    G_CALLBACK (on_PromotionalCode_clicked),
                    NULL);
  g_signal_connect ((gpointer) Statistical, "clicked",
                    G_CALLBACK (on_Statistical_clicked),
                    NULL);
  g_signal_connect ((gpointer) AddMembers, "clicked",
                    G_CALLBACK (on_AddMembers_clicked),
                    NULL);
  g_signal_connect ((gpointer) DeleteMembers, "clicked",
                    G_CALLBACK (on_DeleteMembers_clicked),
                    NULL);
  g_signal_connect ((gpointer) Settings, "clicked",
                    G_CALLBACK (on_Settings_clicked),
                    NULL);
  g_signal_connect ((gpointer) HomePasswordShow, "clicked",
                    G_CALLBACK (on_HomePasswordShow_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (EspaceAdminHome, EspaceAdminHome, "EspaceAdminHome");
  GLADE_HOOKUP_OBJECT (EspaceAdminHome, fixedHome, "fixedHome");
  GLADE_HOOKUP_OBJECT (EspaceAdminHome, hseparator1, "hseparator1");
  GLADE_HOOKUP_OBJECT (EspaceAdminHome, vseparator1, "vseparator1");
  GLADE_HOOKUP_OBJECT (EspaceAdminHome, label2, "label2");
  GLADE_HOOKUP_OBJECT (EspaceAdminHome, labelDashboard, "labelDashboard");
  GLADE_HOOKUP_OBJECT (EspaceAdminHome, Logout, "Logout");
  GLADE_HOOKUP_OBJECT (EspaceAdminHome, Home, "Home");
  GLADE_HOOKUP_OBJECT (EspaceAdminHome, Claims, "Claims");
  GLADE_HOOKUP_OBJECT (EspaceAdminHome, PromotionalCode, "PromotionalCode");
  GLADE_HOOKUP_OBJECT (EspaceAdminHome, Statistical, "Statistical");
  GLADE_HOOKUP_OBJECT (EspaceAdminHome, AddMembers, "AddMembers");
  GLADE_HOOKUP_OBJECT (EspaceAdminHome, DeleteMembers, "DeleteMembers");
  GLADE_HOOKUP_OBJECT (EspaceAdminHome, Settings, "Settings");
  GLADE_HOOKUP_OBJECT (EspaceAdminHome, HomeAgentsNumber, "HomeAgentsNumber");
  GLADE_HOOKUP_OBJECT (EspaceAdminHome, HomeCustomersNumber, "HomeCustomersNumber");
  GLADE_HOOKUP_OBJECT (EspaceAdminHome, label93, "label93");
  GLADE_HOOKUP_OBJECT (EspaceAdminHome, labelAdminsnumber, "labelAdminsnumber");
  GLADE_HOOKUP_OBJECT (EspaceAdminHome, HomeAdminsNumber, "HomeAdminsNumber");
  GLADE_HOOKUP_OBJECT (EspaceAdminHome, labelCustomernumber, "labelCustomernumber");
  GLADE_HOOKUP_OBJECT (EspaceAdminHome, labelAgentsnumber, "labelAgentsnumber");
  GLADE_HOOKUP_OBJECT (EspaceAdminHome, label94, "label94");
  GLADE_HOOKUP_OBJECT (EspaceAdminHome, HomeTotalNumber, "HomeTotalNumber");
  GLADE_HOOKUP_OBJECT (EspaceAdminHome, label96, "label96");
  GLADE_HOOKUP_OBJECT (EspaceAdminHome, label100, "label100");
  GLADE_HOOKUP_OBJECT (EspaceAdminHome, label102, "label102");
  GLADE_HOOKUP_OBJECT (EspaceAdminHome, label104, "label104");
  GLADE_HOOKUP_OBJECT (EspaceAdminHome, HomePasswordShow, "HomePasswordShow");
  GLADE_HOOKUP_OBJECT (EspaceAdminHome, HomePhoneNumber, "HomePhoneNumber");
  GLADE_HOOKUP_OBJECT (EspaceAdminHome, HomeBirthDate, "HomeBirthDate");
  GLADE_HOOKUP_OBJECT (EspaceAdminHome, label98, "label98");
  GLADE_HOOKUP_OBJECT (EspaceAdminHome, HomeEmail, "HomeEmail");
  GLADE_HOOKUP_OBJECT (EspaceAdminHome, HomePassword, "HomePassword");
  GLADE_HOOKUP_OBJECT (EspaceAdminHome, HomeConnectedAs, "HomeConnectedAs");

  return EspaceAdminHome;
}

GtkWidget*
create_EspaceAdminClaims (void)
{
  GtkWidget *EspaceAdminClaims;
  GtkWidget *fixed4;
  GtkWidget *vseparator3;
  GtkWidget *ClaimsTree;
  GtkWidget *label12;
  GtkWidget *hseparator3;
  GtkWidget *label16;
  GtkWidget *Logout;
  GtkWidget *Home;
  GtkWidget *Claims;
  GtkWidget *PromotionalCode;
  GtkWidget *Statistical;
  GtkWidget *AddMembers;
  GtkWidget *DeleteMembers;
  GtkWidget *Settings;
  GtkWidget *ClaimsDone;
  GtkWidget *ClaimsDelete;
  GtkWidget *ClaimsAnswer;

  EspaceAdminClaims = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (EspaceAdminClaims), _("Tunivist"));

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (EspaceAdminClaims), fixed4);

  vseparator3 = gtk_vseparator_new ();
  gtk_widget_show (vseparator3);
  gtk_fixed_put (GTK_FIXED (fixed4), vseparator3, 232, 80);
  gtk_widget_set_size_request (vseparator3, 16, 448);

  ClaimsTree = gtk_tree_view_new ();
  gtk_widget_show (ClaimsTree);
  gtk_fixed_put (GTK_FIXED (fixed4), ClaimsTree, 400, 104);
  gtk_widget_set_size_request (ClaimsTree, 632, 264);

  label12 = gtk_label_new (_("Dashboard"));
  gtk_widget_show (label12);
  gtk_fixed_put (GTK_FIXED (fixed4), label12, 56, 88);
  gtk_widget_set_size_request (label12, 120, 40);
  gtk_misc_set_alignment (GTK_MISC (label12), 0.49, 0.5);

  hseparator3 = gtk_hseparator_new ();
  gtk_widget_show (hseparator3);
  gtk_fixed_put (GTK_FIXED (fixed4), hseparator3, 0, 72);
  gtk_widget_set_size_request (hseparator3, 1168, 16);

  label16 = gtk_label_new (_("Welcome Boss"));
  gtk_widget_show (label16);
  gtk_fixed_put (GTK_FIXED (fixed4), label16, 472, 8);
  gtk_widget_set_size_request (label16, 368, 40);
  gtk_misc_set_alignment (GTK_MISC (label16), 0.5, 0.49);

  Logout = gtk_button_new_with_mnemonic (_("Logout"));
  gtk_widget_show (Logout);
  gtk_fixed_put (GTK_FIXED (fixed4), Logout, 32, 16);
  gtk_widget_set_size_request (Logout, 68, 29);

  Home = gtk_button_new_with_mnemonic (_("Home"));
  gtk_widget_show (Home);
  gtk_fixed_put (GTK_FIXED (fixed4), Home, 40, 136);
  gtk_widget_set_size_request (Home, 144, 40);

  Claims = gtk_button_new_with_mnemonic (_("Claims"));
  gtk_widget_show (Claims);
  gtk_fixed_put (GTK_FIXED (fixed4), Claims, 40, 200);
  gtk_widget_set_size_request (Claims, 144, 32);

  PromotionalCode = gtk_button_new_with_mnemonic (_("Promotional code"));
  gtk_widget_show (PromotionalCode);
  gtk_fixed_put (GTK_FIXED (fixed4), PromotionalCode, 40, 248);
  gtk_widget_set_size_request (PromotionalCode, 144, 40);

  Statistical = gtk_button_new_with_mnemonic (_("Statistical"));
  gtk_widget_show (Statistical);
  gtk_fixed_put (GTK_FIXED (fixed4), Statistical, 40, 304);
  gtk_widget_set_size_request (Statistical, 144, 32);

  AddMembers = gtk_button_new_with_mnemonic (_("Add members"));
  gtk_widget_show (AddMembers);
  gtk_fixed_put (GTK_FIXED (fixed4), AddMembers, 40, 360);
  gtk_widget_set_size_request (AddMembers, 144, 32);

  DeleteMembers = gtk_button_new_with_mnemonic (_("Delete members"));
  gtk_widget_show (DeleteMembers);
  gtk_fixed_put (GTK_FIXED (fixed4), DeleteMembers, 40, 416);
  gtk_widget_set_size_request (DeleteMembers, 144, 32);

  Settings = gtk_button_new_with_mnemonic (_("Settings"));
  gtk_widget_show (Settings);
  gtk_fixed_put (GTK_FIXED (fixed4), Settings, 40, 472);
  gtk_widget_set_size_request (Settings, 144, 32);

  ClaimsDone = gtk_button_new_with_mnemonic (_("Mark As Done"));
  gtk_widget_show (ClaimsDone);
  gtk_fixed_put (GTK_FIXED (fixed4), ClaimsDone, 408, 408);
  gtk_widget_set_size_request (ClaimsDone, 152, 37);

  ClaimsDelete = gtk_button_new_with_mnemonic (_("Delete"));
  gtk_widget_show (ClaimsDelete);
  gtk_fixed_put (GTK_FIXED (fixed4), ClaimsDelete, 664, 408);
  gtk_widget_set_size_request (ClaimsDelete, 144, 37);

  ClaimsAnswer = gtk_button_new_with_mnemonic (_("Answer"));
  gtk_widget_show (ClaimsAnswer);
  gtk_fixed_put (GTK_FIXED (fixed4), ClaimsAnswer, 888, 408);
  gtk_widget_set_size_request (ClaimsAnswer, 144, 37);

  g_signal_connect ((gpointer) Logout, "clicked",
                    G_CALLBACK (on_Logout_clicked),
                    NULL);
  g_signal_connect ((gpointer) Home, "clicked",
                    G_CALLBACK (on_Home_clicked),
                    NULL);
  g_signal_connect ((gpointer) Claims, "clicked",
                    G_CALLBACK (on_Claims_clicked),
                    NULL);
  g_signal_connect ((gpointer) PromotionalCode, "clicked",
                    G_CALLBACK (on_PromotionalCode_clicked),
                    NULL);
  g_signal_connect ((gpointer) Statistical, "clicked",
                    G_CALLBACK (on_Statistical_clicked),
                    NULL);
  g_signal_connect ((gpointer) AddMembers, "clicked",
                    G_CALLBACK (on_AddMembers_clicked),
                    NULL);
  g_signal_connect ((gpointer) DeleteMembers, "clicked",
                    G_CALLBACK (on_DeleteMembers_clicked),
                    NULL);
  g_signal_connect ((gpointer) Settings, "clicked",
                    G_CALLBACK (on_Settings_clicked),
                    NULL);
  g_signal_connect ((gpointer) ClaimsDone, "clicked",
                    G_CALLBACK (on_ClaimsDone_clicked),
                    NULL);
  g_signal_connect ((gpointer) ClaimsDelete, "clicked",
                    G_CALLBACK (on_ClaimsDelete_clicked),
                    NULL);
  g_signal_connect ((gpointer) ClaimsAnswer, "clicked",
                    G_CALLBACK (on_ClaimsAnswer_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (EspaceAdminClaims, EspaceAdminClaims, "EspaceAdminClaims");
  GLADE_HOOKUP_OBJECT (EspaceAdminClaims, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (EspaceAdminClaims, vseparator3, "vseparator3");
  GLADE_HOOKUP_OBJECT (EspaceAdminClaims, ClaimsTree, "ClaimsTree");
  GLADE_HOOKUP_OBJECT (EspaceAdminClaims, label12, "label12");
  GLADE_HOOKUP_OBJECT (EspaceAdminClaims, hseparator3, "hseparator3");
  GLADE_HOOKUP_OBJECT (EspaceAdminClaims, label16, "label16");
  GLADE_HOOKUP_OBJECT (EspaceAdminClaims, Logout, "Logout");
  GLADE_HOOKUP_OBJECT (EspaceAdminClaims, Home, "Home");
  GLADE_HOOKUP_OBJECT (EspaceAdminClaims, Claims, "Claims");
  GLADE_HOOKUP_OBJECT (EspaceAdminClaims, PromotionalCode, "PromotionalCode");
  GLADE_HOOKUP_OBJECT (EspaceAdminClaims, Statistical, "Statistical");
  GLADE_HOOKUP_OBJECT (EspaceAdminClaims, AddMembers, "AddMembers");
  GLADE_HOOKUP_OBJECT (EspaceAdminClaims, DeleteMembers, "DeleteMembers");
  GLADE_HOOKUP_OBJECT (EspaceAdminClaims, Settings, "Settings");
  GLADE_HOOKUP_OBJECT (EspaceAdminClaims, ClaimsDone, "ClaimsDone");
  GLADE_HOOKUP_OBJECT (EspaceAdminClaims, ClaimsDelete, "ClaimsDelete");
  GLADE_HOOKUP_OBJECT (EspaceAdminClaims, ClaimsAnswer, "ClaimsAnswer");

  return EspaceAdminClaims;
}

GtkWidget*
create_EspaceAdminClaimsAnswer (void)
{
  GtkWidget *EspaceAdminClaimsAnswer;
  GtkWidget *fixed5;
  GtkWidget *fixed6;
  GtkWidget *hseparator4;
  GtkWidget *vseparator4;
  GtkWidget *label30;
  GtkWidget *entry1;
  GtkWidget *label26;
  GtkWidget *Logout;
  GtkWidget *Home;
  GtkWidget *Claims;
  GtkWidget *PromotionalCode;
  GtkWidget *Statistical;
  GtkWidget *AddMembers;
  GtkWidget *DeleteMembers;
  GtkWidget *Settings;
  GtkWidget *ClaimsAnswerSend;

  EspaceAdminClaimsAnswer = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (EspaceAdminClaimsAnswer), _("Tunivisit"));

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (EspaceAdminClaimsAnswer), fixed5);

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_fixed_put (GTK_FIXED (fixed5), fixed6, 0, 0);
  gtk_widget_set_size_request (fixed6, 0, 0);

  hseparator4 = gtk_hseparator_new ();
  gtk_widget_show (hseparator4);
  gtk_fixed_put (GTK_FIXED (fixed6), hseparator4, 0, 72);
  gtk_widget_set_size_request (hseparator4, 1168, 16);

  vseparator4 = gtk_vseparator_new ();
  gtk_widget_show (vseparator4);
  gtk_fixed_put (GTK_FIXED (fixed6), vseparator4, 232, 80);
  gtk_widget_set_size_request (vseparator4, 16, 448);

  label30 = gtk_label_new (_("Welcome Boss"));
  gtk_widget_show (label30);
  gtk_fixed_put (GTK_FIXED (fixed6), label30, 472, 8);
  gtk_widget_set_size_request (label30, 368, 40);
  gtk_misc_set_alignment (GTK_MISC (label30), 0.5, 0.49);

  entry1 = gtk_entry_new ();
  gtk_widget_show (entry1);
  gtk_fixed_put (GTK_FIXED (fixed6), entry1, 456, 120);
  gtk_widget_set_size_request (entry1, 496, 272);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1), 8226);

  label26 = gtk_label_new (_("Dashboard"));
  gtk_widget_show (label26);
  gtk_fixed_put (GTK_FIXED (fixed6), label26, 56, 88);
  gtk_widget_set_size_request (label26, 120, 40);
  gtk_misc_set_alignment (GTK_MISC (label26), 0.49, 0.5);

  Logout = gtk_button_new_with_mnemonic (_("Logout"));
  gtk_widget_show (Logout);
  gtk_fixed_put (GTK_FIXED (fixed6), Logout, 32, 16);
  gtk_widget_set_size_request (Logout, 68, 29);

  Home = gtk_button_new_with_mnemonic (_("Home"));
  gtk_widget_show (Home);
  gtk_fixed_put (GTK_FIXED (fixed6), Home, 40, 144);
  gtk_widget_set_size_request (Home, 144, 40);

  Claims = gtk_button_new_with_mnemonic (_("Claims"));
  gtk_widget_show (Claims);
  gtk_fixed_put (GTK_FIXED (fixed6), Claims, 40, 208);
  gtk_widget_set_size_request (Claims, 144, 32);

  PromotionalCode = gtk_button_new_with_mnemonic (_("Promotional code"));
  gtk_widget_show (PromotionalCode);
  gtk_fixed_put (GTK_FIXED (fixed6), PromotionalCode, 40, 256);
  gtk_widget_set_size_request (PromotionalCode, 144, 32);

  Statistical = gtk_button_new_with_mnemonic (_("Statistical"));
  gtk_widget_show (Statistical);
  gtk_fixed_put (GTK_FIXED (fixed6), Statistical, 40, 304);
  gtk_widget_set_size_request (Statistical, 144, 32);

  AddMembers = gtk_button_new_with_mnemonic (_("Add members"));
  gtk_widget_show (AddMembers);
  gtk_fixed_put (GTK_FIXED (fixed6), AddMembers, 40, 360);
  gtk_widget_set_size_request (AddMembers, 144, 32);

  DeleteMembers = gtk_button_new_with_mnemonic (_("Delete members"));
  gtk_widget_show (DeleteMembers);
  gtk_fixed_put (GTK_FIXED (fixed6), DeleteMembers, 40, 416);
  gtk_widget_set_size_request (DeleteMembers, 144, 32);

  Settings = gtk_button_new_with_mnemonic (_("Settings"));
  gtk_widget_show (Settings);
  gtk_fixed_put (GTK_FIXED (fixed6), Settings, 40, 472);
  gtk_widget_set_size_request (Settings, 144, 32);

  ClaimsAnswerSend = gtk_button_new_with_mnemonic (_("Send"));
  gtk_widget_show (ClaimsAnswerSend);
  gtk_fixed_put (GTK_FIXED (fixed6), ClaimsAnswerSend, 672, 424);
  gtk_widget_set_size_request (ClaimsAnswerSend, 76, 29);

  g_signal_connect ((gpointer) Logout, "clicked",
                    G_CALLBACK (on_Logout_clicked),
                    NULL);
  g_signal_connect ((gpointer) Home, "clicked",
                    G_CALLBACK (on_Home_clicked),
                    NULL);
  g_signal_connect ((gpointer) Claims, "clicked",
                    G_CALLBACK (on_Claims_clicked),
                    NULL);
  g_signal_connect ((gpointer) PromotionalCode, "clicked",
                    G_CALLBACK (on_PromotionalCode_clicked),
                    NULL);
  g_signal_connect ((gpointer) Statistical, "clicked",
                    G_CALLBACK (on_Statistical_clicked),
                    NULL);
  g_signal_connect ((gpointer) AddMembers, "clicked",
                    G_CALLBACK (on_AddMembers_clicked),
                    NULL);
  g_signal_connect ((gpointer) DeleteMembers, "clicked",
                    G_CALLBACK (on_DeleteMembers_clicked),
                    NULL);
  g_signal_connect ((gpointer) Settings, "clicked",
                    G_CALLBACK (on_Settings_clicked),
                    NULL);
  g_signal_connect ((gpointer) ClaimsAnswerSend, "clicked",
                    G_CALLBACK (on_ClaimsAnswerSend_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (EspaceAdminClaimsAnswer, EspaceAdminClaimsAnswer, "EspaceAdminClaimsAnswer");
  GLADE_HOOKUP_OBJECT (EspaceAdminClaimsAnswer, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (EspaceAdminClaimsAnswer, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (EspaceAdminClaimsAnswer, hseparator4, "hseparator4");
  GLADE_HOOKUP_OBJECT (EspaceAdminClaimsAnswer, vseparator4, "vseparator4");
  GLADE_HOOKUP_OBJECT (EspaceAdminClaimsAnswer, label30, "label30");
  GLADE_HOOKUP_OBJECT (EspaceAdminClaimsAnswer, entry1, "entry1");
  GLADE_HOOKUP_OBJECT (EspaceAdminClaimsAnswer, label26, "label26");
  GLADE_HOOKUP_OBJECT (EspaceAdminClaimsAnswer, Logout, "Logout");
  GLADE_HOOKUP_OBJECT (EspaceAdminClaimsAnswer, Home, "Home");
  GLADE_HOOKUP_OBJECT (EspaceAdminClaimsAnswer, Claims, "Claims");
  GLADE_HOOKUP_OBJECT (EspaceAdminClaimsAnswer, PromotionalCode, "PromotionalCode");
  GLADE_HOOKUP_OBJECT (EspaceAdminClaimsAnswer, Statistical, "Statistical");
  GLADE_HOOKUP_OBJECT (EspaceAdminClaimsAnswer, AddMembers, "AddMembers");
  GLADE_HOOKUP_OBJECT (EspaceAdminClaimsAnswer, DeleteMembers, "DeleteMembers");
  GLADE_HOOKUP_OBJECT (EspaceAdminClaimsAnswer, Settings, "Settings");
  GLADE_HOOKUP_OBJECT (EspaceAdminClaimsAnswer, ClaimsAnswerSend, "ClaimsAnswerSend");

  return EspaceAdminClaimsAnswer;
}

GtkWidget*
create_EspaceAdminStatistical (void)
{
  GtkWidget *EspaceAdminStatistical;
  GtkWidget *fixed8;
  GtkWidget *hseparator5;
  GtkWidget *vseparator5;
  GtkWidget *label43;
  GtkWidget *StatisticalsAgent;
  GtkWidget *label41;
  GtkWidget *label40;
  GtkWidget *label42;
  GtkWidget *label92;
  GtkWidget *StatisticalsDemandsDone;
  GtkWidget *StatisticalsPerformance;
  GtkWidget *StatisticalsHoursOnline;
  GtkWidget *label39;
  GtkWidget *Logout;
  GtkWidget *Home;
  GtkWidget *Claims;
  GtkWidget *PromotionalCode;
  GtkWidget *Statistical;
  GtkWidget *AddMembers;
  GtkWidget *DeleteMembers;
  GtkWidget *Settings;

  EspaceAdminStatistical = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (EspaceAdminStatistical), _("Tunivist"));

  fixed8 = gtk_fixed_new ();
  gtk_widget_show (fixed8);
  gtk_container_add (GTK_CONTAINER (EspaceAdminStatistical), fixed8);

  hseparator5 = gtk_hseparator_new ();
  gtk_widget_show (hseparator5);
  gtk_fixed_put (GTK_FIXED (fixed8), hseparator5, 0, 72);
  gtk_widget_set_size_request (hseparator5, 1168, 16);

  vseparator5 = gtk_vseparator_new ();
  gtk_widget_show (vseparator5);
  gtk_fixed_put (GTK_FIXED (fixed8), vseparator5, 232, 80);
  gtk_widget_set_size_request (vseparator5, 16, 448);

  label43 = gtk_label_new (_("Welcome Boss"));
  gtk_widget_show (label43);
  gtk_fixed_put (GTK_FIXED (fixed8), label43, 472, 8);
  gtk_widget_set_size_request (label43, 368, 40);
  gtk_misc_set_alignment (GTK_MISC (label43), 0.5, 0.49);

  StatisticalsAgent = gtk_combo_box_new_text ();
  gtk_widget_show (StatisticalsAgent);
  gtk_fixed_put (GTK_FIXED (fixed8), StatisticalsAgent, 640, 148);
  gtk_widget_set_size_request (StatisticalsAgent, 210, 33);

  label41 = gtk_label_new (_("Agent:"));
  gtk_widget_show (label41);
  gtk_fixed_put (GTK_FIXED (fixed8), label41, 480, 144);
  gtk_widget_set_size_request (label41, 192, 40);

  label40 = gtk_label_new (_("Hours Online:"));
  gtk_widget_show (label40);
  gtk_fixed_put (GTK_FIXED (fixed8), label40, 336, 232);
  gtk_widget_set_size_request (label40, 129, 32);

  label42 = gtk_label_new (_("Demands Done:"));
  gtk_widget_show (label42);
  gtk_fixed_put (GTK_FIXED (fixed8), label42, 600, 224);
  gtk_widget_set_size_request (label42, 168, 40);

  label92 = gtk_label_new (_("Performance:"));
  gtk_widget_show (label92);
  gtk_fixed_put (GTK_FIXED (fixed8), label92, 880, 224);
  gtk_widget_set_size_request (label92, 216, 32);

  StatisticalsDemandsDone = gtk_label_new (_("0"));
  gtk_widget_show (StatisticalsDemandsDone);
  gtk_fixed_put (GTK_FIXED (fixed8), StatisticalsDemandsDone, 624, 280);
  gtk_widget_set_size_request (StatisticalsDemandsDone, 120, 40);

  StatisticalsPerformance = gtk_label_new (_("0"));
  gtk_widget_show (StatisticalsPerformance);
  gtk_fixed_put (GTK_FIXED (fixed8), StatisticalsPerformance, 928, 280);
  gtk_widget_set_size_request (StatisticalsPerformance, 128, 40);

  StatisticalsHoursOnline = gtk_label_new (_("0"));
  gtk_widget_show (StatisticalsHoursOnline);
  gtk_fixed_put (GTK_FIXED (fixed8), StatisticalsHoursOnline, 336, 280);
  gtk_widget_set_size_request (StatisticalsHoursOnline, 128, 40);

  label39 = gtk_label_new (_("Dashboard"));
  gtk_widget_show (label39);
  gtk_fixed_put (GTK_FIXED (fixed8), label39, 56, 88);
  gtk_widget_set_size_request (label39, 120, 40);
  gtk_misc_set_alignment (GTK_MISC (label39), 0.49, 0.5);

  Logout = gtk_button_new_with_mnemonic (_("Logout"));
  gtk_widget_show (Logout);
  gtk_fixed_put (GTK_FIXED (fixed8), Logout, 32, 16);
  gtk_widget_set_size_request (Logout, 68, 29);

  Home = gtk_button_new_with_mnemonic (_("Home"));
  gtk_widget_show (Home);
  gtk_fixed_put (GTK_FIXED (fixed8), Home, 40, 144);
  gtk_widget_set_size_request (Home, 144, 40);

  Claims = gtk_button_new_with_mnemonic (_("Claims"));
  gtk_widget_show (Claims);
  gtk_fixed_put (GTK_FIXED (fixed8), Claims, 40, 208);
  gtk_widget_set_size_request (Claims, 144, 32);

  PromotionalCode = gtk_button_new_with_mnemonic (_("Promotional code"));
  gtk_widget_show (PromotionalCode);
  gtk_fixed_put (GTK_FIXED (fixed8), PromotionalCode, 40, 256);
  gtk_widget_set_size_request (PromotionalCode, 144, 29);

  Statistical = gtk_button_new_with_mnemonic (_("Statistical"));
  gtk_widget_show (Statistical);
  gtk_fixed_put (GTK_FIXED (fixed8), Statistical, 40, 304);
  gtk_widget_set_size_request (Statistical, 144, 32);

  AddMembers = gtk_button_new_with_mnemonic (_("Add members"));
  gtk_widget_show (AddMembers);
  gtk_fixed_put (GTK_FIXED (fixed8), AddMembers, 40, 360);
  gtk_widget_set_size_request (AddMembers, 144, 32);

  DeleteMembers = gtk_button_new_with_mnemonic (_("Delete members"));
  gtk_widget_show (DeleteMembers);
  gtk_fixed_put (GTK_FIXED (fixed8), DeleteMembers, 40, 416);
  gtk_widget_set_size_request (DeleteMembers, 144, 32);

  Settings = gtk_button_new_with_mnemonic (_("Settings"));
  gtk_widget_show (Settings);
  gtk_fixed_put (GTK_FIXED (fixed8), Settings, 40, 472);
  gtk_widget_set_size_request (Settings, 144, 32);

  g_signal_connect ((gpointer) EspaceAdminStatistical, "show",
                    G_CALLBACK (on_EspaceAdminStatistical_show),
                    NULL);
  g_signal_connect ((gpointer) Logout, "clicked",
                    G_CALLBACK (on_Logout_clicked),
                    NULL);
  g_signal_connect ((gpointer) Home, "clicked",
                    G_CALLBACK (on_Home_clicked),
                    NULL);
  g_signal_connect ((gpointer) Claims, "clicked",
                    G_CALLBACK (on_Claims_clicked),
                    NULL);
  g_signal_connect ((gpointer) PromotionalCode, "clicked",
                    G_CALLBACK (on_PromotionalCode_clicked),
                    NULL);
  g_signal_connect ((gpointer) Statistical, "clicked",
                    G_CALLBACK (on_Statistical_clicked),
                    NULL);
  g_signal_connect ((gpointer) AddMembers, "clicked",
                    G_CALLBACK (on_AddMembers_clicked),
                    NULL);
  g_signal_connect ((gpointer) DeleteMembers, "clicked",
                    G_CALLBACK (on_DeleteMembers_clicked),
                    NULL);
  g_signal_connect ((gpointer) Settings, "clicked",
                    G_CALLBACK (on_Settings_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (EspaceAdminStatistical, EspaceAdminStatistical, "EspaceAdminStatistical");
  GLADE_HOOKUP_OBJECT (EspaceAdminStatistical, fixed8, "fixed8");
  GLADE_HOOKUP_OBJECT (EspaceAdminStatistical, hseparator5, "hseparator5");
  GLADE_HOOKUP_OBJECT (EspaceAdminStatistical, vseparator5, "vseparator5");
  GLADE_HOOKUP_OBJECT (EspaceAdminStatistical, label43, "label43");
  GLADE_HOOKUP_OBJECT (EspaceAdminStatistical, StatisticalsAgent, "StatisticalsAgent");
  GLADE_HOOKUP_OBJECT (EspaceAdminStatistical, label41, "label41");
  GLADE_HOOKUP_OBJECT (EspaceAdminStatistical, label40, "label40");
  GLADE_HOOKUP_OBJECT (EspaceAdminStatistical, label42, "label42");
  GLADE_HOOKUP_OBJECT (EspaceAdminStatistical, label92, "label92");
  GLADE_HOOKUP_OBJECT (EspaceAdminStatistical, StatisticalsDemandsDone, "StatisticalsDemandsDone");
  GLADE_HOOKUP_OBJECT (EspaceAdminStatistical, StatisticalsPerformance, "StatisticalsPerformance");
  GLADE_HOOKUP_OBJECT (EspaceAdminStatistical, StatisticalsHoursOnline, "StatisticalsHoursOnline");
  GLADE_HOOKUP_OBJECT (EspaceAdminStatistical, label39, "label39");
  GLADE_HOOKUP_OBJECT (EspaceAdminStatistical, Logout, "Logout");
  GLADE_HOOKUP_OBJECT (EspaceAdminStatistical, Home, "Home");
  GLADE_HOOKUP_OBJECT (EspaceAdminStatistical, Claims, "Claims");
  GLADE_HOOKUP_OBJECT (EspaceAdminStatistical, PromotionalCode, "PromotionalCode");
  GLADE_HOOKUP_OBJECT (EspaceAdminStatistical, Statistical, "Statistical");
  GLADE_HOOKUP_OBJECT (EspaceAdminStatistical, AddMembers, "AddMembers");
  GLADE_HOOKUP_OBJECT (EspaceAdminStatistical, DeleteMembers, "DeleteMembers");
  GLADE_HOOKUP_OBJECT (EspaceAdminStatistical, Settings, "Settings");

  return EspaceAdminStatistical;
}

GtkWidget*
create_EspaceAdminAddmemberInfo (void)
{
  GtkWidget *EspaceAdminAddmemberInfo;
  GtkWidget *fixed11;
  GtkWidget *label71;
  GtkWidget *label65;
  GtkWidget *label66;
  GtkWidget *AddMembersName;
  GtkWidget *AddMembersFName;
  GtkWidget *AddMembersPhone;
  GtkWidget *AddMembersNationalID;
  GtkWidget *AddMembersEmail;
  GtkWidget *AddMembersPassword;
  GtkWidget *AddMembersCPassword;
  GtkWidget *label82;
  GtkWidget *label83;
  GtkWidget *hseparator7;
  GtkWidget *label53;
  GtkWidget *label69;
  GtkWidget *label67;
  GtkObject *AddMembersBirthDay_adj;
  GtkWidget *AddMembersBirthDay;
  GtkObject *AddMembersBirthMonth_adj;
  GtkWidget *AddMembersBirthMonth;
  GtkObject *AddMembersBirthYear_adj;
  GtkWidget *AddMembersBirthYear;
  GtkWidget *label70;
  GtkWidget *label87;
  GtkWidget *label88;
  GtkWidget *label89;
  GtkWidget *Logout;
  GtkWidget *AddMembers;
  GtkWidget *DeleteMembers;
  GtkWidget *Settings;
  GtkWidget *label49;
  GtkWidget *Home;
  GtkWidget *Claims;
  GtkWidget *PromotionalCode;
  GtkWidget *Statistical;
  GtkWidget *AddMembersUploadCV;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label73;
  GtkWidget *AddMembersRole;
  GtkWidget *AddMembersAdd;
  GtkWidget *label68;
  GtkWidget *AddMembersEmptyInfo;
  GtkWidget *AddMembersWrongPassword;
  GtkWidget *vseparator7;

  EspaceAdminAddmemberInfo = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (EspaceAdminAddmemberInfo), _("Tunivisit"));

  fixed11 = gtk_fixed_new ();
  gtk_widget_show (fixed11);
  gtk_container_add (GTK_CONTAINER (EspaceAdminAddmemberInfo), fixed11);

  label71 = gtk_label_new (_("Role:"));
  gtk_widget_show (label71);
  gtk_fixed_put (GTK_FIXED (fixed11), label71, 584, 112);
  gtk_widget_set_size_request (label71, 65, 24);

  label65 = gtk_label_new (_("Name:"));
  gtk_widget_show (label65);
  gtk_fixed_put (GTK_FIXED (fixed11), label65, 504, 168);
  gtk_widget_set_size_request (label65, 80, 24);

  label66 = gtk_label_new (_("Family Name:"));
  gtk_widget_show (label66);
  gtk_fixed_put (GTK_FIXED (fixed11), label66, 464, 216);
  gtk_widget_set_size_request (label66, 112, 24);

  AddMembersName = gtk_entry_new ();
  gtk_widget_show (AddMembersName);
  gtk_fixed_put (GTK_FIXED (fixed11), AddMembersName, 576, 168);
  gtk_widget_set_size_request (AddMembersName, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (AddMembersName), 8226);

  AddMembersFName = gtk_entry_new ();
  gtk_widget_show (AddMembersFName);
  gtk_fixed_put (GTK_FIXED (fixed11), AddMembersFName, 576, 216);
  gtk_widget_set_size_request (AddMembersFName, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (AddMembersFName), 8226);

  AddMembersPhone = gtk_entry_new ();
  gtk_widget_show (AddMembersPhone);
  gtk_fixed_put (GTK_FIXED (fixed11), AddMembersPhone, 576, 320);
  gtk_widget_set_size_request (AddMembersPhone, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (AddMembersPhone), 8226);

  AddMembersNationalID = gtk_entry_new ();
  gtk_widget_show (AddMembersNationalID);
  gtk_fixed_put (GTK_FIXED (fixed11), AddMembersNationalID, 928, 176);
  gtk_widget_set_size_request (AddMembersNationalID, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (AddMembersNationalID), 8226);

  AddMembersEmail = gtk_entry_new ();
  gtk_widget_show (AddMembersEmail);
  gtk_fixed_put (GTK_FIXED (fixed11), AddMembersEmail, 928, 240);
  gtk_widget_set_size_request (AddMembersEmail, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (AddMembersEmail), 8226);

  AddMembersPassword = gtk_entry_new ();
  gtk_widget_show (AddMembersPassword);
  gtk_fixed_put (GTK_FIXED (fixed11), AddMembersPassword, 576, 376);
  gtk_widget_set_size_request (AddMembersPassword, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (AddMembersPassword), 8226);

  AddMembersCPassword = gtk_entry_new ();
  gtk_widget_show (AddMembersCPassword);
  gtk_fixed_put (GTK_FIXED (fixed11), AddMembersCPassword, 576, 424);
  gtk_widget_set_size_request (AddMembersCPassword, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (AddMembersCPassword), 8226);

  label82 = gtk_label_new (_("Password:"));
  gtk_widget_show (label82);
  gtk_fixed_put (GTK_FIXED (fixed11), label82, 488, 376);
  gtk_widget_set_size_request (label82, 96, 24);

  label83 = gtk_label_new (_("Repeat Password:"));
  gtk_widget_show (label83);
  gtk_fixed_put (GTK_FIXED (fixed11), label83, 440, 424);
  gtk_widget_set_size_request (label83, 136, 24);

  hseparator7 = gtk_hseparator_new ();
  gtk_widget_show (hseparator7);
  gtk_fixed_put (GTK_FIXED (fixed11), hseparator7, 0, 72);
  gtk_widget_set_size_request (hseparator7, 1168, 16);

  label53 = gtk_label_new (_("Welcome Boss"));
  gtk_widget_show (label53);
  gtk_fixed_put (GTK_FIXED (fixed11), label53, 472, 8);
  gtk_widget_set_size_request (label53, 368, 40);
  gtk_misc_set_alignment (GTK_MISC (label53), 0.5, 0.49);

  label69 = gtk_label_new (_("National ID:"));
  gtk_widget_show (label69);
  gtk_fixed_put (GTK_FIXED (fixed11), label69, 808, 184);
  gtk_widget_set_size_request (label69, 112, 24);

  label67 = gtk_label_new (_("Email:"));
  gtk_widget_show (label67);
  gtk_fixed_put (GTK_FIXED (fixed11), label67, 824, 240);
  gtk_widget_set_size_request (label67, 112, 32);

  AddMembersBirthDay_adj = gtk_adjustment_new (1, 1, 32, 1, 10, 10);
  AddMembersBirthDay = gtk_spin_button_new (GTK_ADJUSTMENT (AddMembersBirthDay_adj), 1, 0);
  gtk_widget_show (AddMembersBirthDay);
  gtk_fixed_put (GTK_FIXED (fixed11), AddMembersBirthDay, 488, 264);
  gtk_widget_set_size_request (AddMembersBirthDay, 60, 27);

  AddMembersBirthMonth_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  AddMembersBirthMonth = gtk_spin_button_new (GTK_ADJUSTMENT (AddMembersBirthMonth_adj), 1, 0);
  gtk_widget_show (AddMembersBirthMonth);
  gtk_fixed_put (GTK_FIXED (fixed11), AddMembersBirthMonth, 624, 264);
  gtk_widget_set_size_request (AddMembersBirthMonth, 60, 27);

  AddMembersBirthYear_adj = gtk_adjustment_new (1960, 1960, 2001, 1, 10, 10);
  AddMembersBirthYear = gtk_spin_button_new (GTK_ADJUSTMENT (AddMembersBirthYear_adj), 1, 0);
  gtk_widget_show (AddMembersBirthYear);
  gtk_fixed_put (GTK_FIXED (fixed11), AddMembersBirthYear, 752, 264);
  gtk_widget_set_size_request (AddMembersBirthYear, 60, 27);

  label70 = gtk_label_new (_("Birth Date:"));
  gtk_widget_show (label70);
  gtk_fixed_put (GTK_FIXED (fixed11), label70, 312, 264);
  gtk_widget_set_size_request (label70, 120, 32);

  label87 = gtk_label_new (_("Day"));
  gtk_widget_show (label87);
  gtk_fixed_put (GTK_FIXED (fixed11), label87, 440, 272);
  gtk_widget_set_size_request (label87, 49, 17);

  label88 = gtk_label_new (_("Month"));
  gtk_widget_show (label88);
  gtk_fixed_put (GTK_FIXED (fixed11), label88, 568, 272);
  gtk_widget_set_size_request (label88, 57, 16);

  label89 = gtk_label_new (_("Year"));
  gtk_widget_show (label89);
  gtk_fixed_put (GTK_FIXED (fixed11), label89, 696, 264);
  gtk_widget_set_size_request (label89, 57, 25);

  Logout = gtk_button_new_with_mnemonic (_("Logout"));
  gtk_widget_show (Logout);
  gtk_fixed_put (GTK_FIXED (fixed11), Logout, 32, 16);
  gtk_widget_set_size_request (Logout, 68, 29);

  AddMembers = gtk_button_new_with_mnemonic (_("Add members"));
  gtk_widget_show (AddMembers);
  gtk_fixed_put (GTK_FIXED (fixed11), AddMembers, 40, 360);
  gtk_widget_set_size_request (AddMembers, 144, 32);

  DeleteMembers = gtk_button_new_with_mnemonic (_("Delete members"));
  gtk_widget_show (DeleteMembers);
  gtk_fixed_put (GTK_FIXED (fixed11), DeleteMembers, 40, 416);
  gtk_widget_set_size_request (DeleteMembers, 144, 32);

  Settings = gtk_button_new_with_mnemonic (_("Settings"));
  gtk_widget_show (Settings);
  gtk_fixed_put (GTK_FIXED (fixed11), Settings, 40, 472);
  gtk_widget_set_size_request (Settings, 144, 32);

  label49 = gtk_label_new (_("Dashboard"));
  gtk_widget_show (label49);
  gtk_fixed_put (GTK_FIXED (fixed11), label49, 56, 88);
  gtk_widget_set_size_request (label49, 120, 40);
  gtk_misc_set_alignment (GTK_MISC (label49), 0.49, 0.5);

  Home = gtk_button_new_with_mnemonic (_("Home"));
  gtk_widget_show (Home);
  gtk_fixed_put (GTK_FIXED (fixed11), Home, 40, 136);
  gtk_widget_set_size_request (Home, 144, 40);

  Claims = gtk_button_new_with_mnemonic (_("Claims"));
  gtk_widget_show (Claims);
  gtk_fixed_put (GTK_FIXED (fixed11), Claims, 40, 200);
  gtk_widget_set_size_request (Claims, 144, 32);

  PromotionalCode = gtk_button_new_with_mnemonic (_("Promotional code"));
  gtk_widget_show (PromotionalCode);
  gtk_fixed_put (GTK_FIXED (fixed11), PromotionalCode, 40, 248);
  gtk_widget_set_size_request (PromotionalCode, 144, 37);

  Statistical = gtk_button_new_with_mnemonic (_("Statistical"));
  gtk_widget_show (Statistical);
  gtk_fixed_put (GTK_FIXED (fixed11), Statistical, 40, 304);
  gtk_widget_set_size_request (Statistical, 144, 32);

  AddMembersUploadCV = gtk_button_new ();
  gtk_widget_show (AddMembersUploadCV);
  gtk_fixed_put (GTK_FIXED (fixed11), AddMembersUploadCV, 944, 320);
  gtk_widget_set_size_request (AddMembersUploadCV, 104, 32);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (AddMembersUploadCV), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-orientation-portrait", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label73 = gtk_label_new_with_mnemonic (_("Upload CV"));
  gtk_widget_show (label73);
  gtk_box_pack_start (GTK_BOX (hbox1), label73, FALSE, FALSE, 0);

  AddMembersRole = gtk_combo_box_new_text ();
  gtk_widget_show (AddMembersRole);
  gtk_fixed_put (GTK_FIXED (fixed11), AddMembersRole, 648, 110);
  gtk_widget_set_size_request (AddMembersRole, 188, 31);
  gtk_combo_box_append_text (GTK_COMBO_BOX (AddMembersRole), _("Admin"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (AddMembersRole), _("Agent"));

  AddMembersAdd = gtk_button_new_with_mnemonic (_("Add"));
  gtk_widget_show (AddMembersAdd);
  gtk_fixed_put (GTK_FIXED (fixed11), AddMembersAdd, 960, 384);
  gtk_widget_set_size_request (AddMembersAdd, 76, 29);

  label68 = gtk_label_new (_("Phone number:"));
  gtk_widget_show (label68);
  gtk_fixed_put (GTK_FIXED (fixed11), label68, 464, 320);
  gtk_widget_set_size_request (label68, 112, 32);

  AddMembersEmptyInfo = gtk_label_new ("");
  gtk_widget_show (AddMembersEmptyInfo);
  gtk_fixed_put (GTK_FIXED (fixed11), AddMembersEmptyInfo, 880, 464);
  gtk_widget_set_size_request (AddMembersEmptyInfo, 224, 24);

  AddMembersWrongPassword = gtk_label_new ("");
  gtk_widget_show (AddMembersWrongPassword);
  gtk_fixed_put (GTK_FIXED (fixed11), AddMembersWrongPassword, 880, 424);
  gtk_widget_set_size_request (AddMembersWrongPassword, 224, 24);

  vseparator7 = gtk_vseparator_new ();
  gtk_widget_show (vseparator7);
  gtk_fixed_put (GTK_FIXED (fixed11), vseparator7, 232, 80);
  gtk_widget_set_size_request (vseparator7, 16, 448);

  g_signal_connect ((gpointer) Logout, "clicked",
                    G_CALLBACK (on_Logout_clicked),
                    NULL);
  g_signal_connect ((gpointer) AddMembers, "clicked",
                    G_CALLBACK (on_AddMembers_clicked),
                    NULL);
  g_signal_connect ((gpointer) DeleteMembers, "clicked",
                    G_CALLBACK (on_DeleteMembers_clicked),
                    NULL);
  g_signal_connect ((gpointer) Settings, "clicked",
                    G_CALLBACK (on_Settings_clicked),
                    NULL);
  g_signal_connect ((gpointer) Home, "clicked",
                    G_CALLBACK (on_Home_clicked),
                    NULL);
  g_signal_connect ((gpointer) Claims, "clicked",
                    G_CALLBACK (on_Claims_clicked),
                    NULL);
  g_signal_connect ((gpointer) PromotionalCode, "clicked",
                    G_CALLBACK (on_PromotionalCode_clicked),
                    NULL);
  g_signal_connect ((gpointer) Statistical, "clicked",
                    G_CALLBACK (on_Statistical_clicked),
                    NULL);
  g_signal_connect ((gpointer) AddMembersUploadCV, "clicked",
                    G_CALLBACK (on_AddMembersUploadCV_clicked),
                    NULL);
  g_signal_connect ((gpointer) AddMembersAdd, "clicked",
                    G_CALLBACK (on_AddMembersAdd_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (EspaceAdminAddmemberInfo, EspaceAdminAddmemberInfo, "EspaceAdminAddmemberInfo");
  GLADE_HOOKUP_OBJECT (EspaceAdminAddmemberInfo, fixed11, "fixed11");
  GLADE_HOOKUP_OBJECT (EspaceAdminAddmemberInfo, label71, "label71");
  GLADE_HOOKUP_OBJECT (EspaceAdminAddmemberInfo, label65, "label65");
  GLADE_HOOKUP_OBJECT (EspaceAdminAddmemberInfo, label66, "label66");
  GLADE_HOOKUP_OBJECT (EspaceAdminAddmemberInfo, AddMembersName, "AddMembersName");
  GLADE_HOOKUP_OBJECT (EspaceAdminAddmemberInfo, AddMembersFName, "AddMembersFName");
  GLADE_HOOKUP_OBJECT (EspaceAdminAddmemberInfo, AddMembersPhone, "AddMembersPhone");
  GLADE_HOOKUP_OBJECT (EspaceAdminAddmemberInfo, AddMembersNationalID, "AddMembersNationalID");
  GLADE_HOOKUP_OBJECT (EspaceAdminAddmemberInfo, AddMembersEmail, "AddMembersEmail");
  GLADE_HOOKUP_OBJECT (EspaceAdminAddmemberInfo, AddMembersPassword, "AddMembersPassword");
  GLADE_HOOKUP_OBJECT (EspaceAdminAddmemberInfo, AddMembersCPassword, "AddMembersCPassword");
  GLADE_HOOKUP_OBJECT (EspaceAdminAddmemberInfo, label82, "label82");
  GLADE_HOOKUP_OBJECT (EspaceAdminAddmemberInfo, label83, "label83");
  GLADE_HOOKUP_OBJECT (EspaceAdminAddmemberInfo, hseparator7, "hseparator7");
  GLADE_HOOKUP_OBJECT (EspaceAdminAddmemberInfo, label53, "label53");
  GLADE_HOOKUP_OBJECT (EspaceAdminAddmemberInfo, label69, "label69");
  GLADE_HOOKUP_OBJECT (EspaceAdminAddmemberInfo, label67, "label67");
  GLADE_HOOKUP_OBJECT (EspaceAdminAddmemberInfo, AddMembersBirthDay, "AddMembersBirthDay");
  GLADE_HOOKUP_OBJECT (EspaceAdminAddmemberInfo, AddMembersBirthMonth, "AddMembersBirthMonth");
  GLADE_HOOKUP_OBJECT (EspaceAdminAddmemberInfo, AddMembersBirthYear, "AddMembersBirthYear");
  GLADE_HOOKUP_OBJECT (EspaceAdminAddmemberInfo, label70, "label70");
  GLADE_HOOKUP_OBJECT (EspaceAdminAddmemberInfo, label87, "label87");
  GLADE_HOOKUP_OBJECT (EspaceAdminAddmemberInfo, label88, "label88");
  GLADE_HOOKUP_OBJECT (EspaceAdminAddmemberInfo, label89, "label89");
  GLADE_HOOKUP_OBJECT (EspaceAdminAddmemberInfo, Logout, "Logout");
  GLADE_HOOKUP_OBJECT (EspaceAdminAddmemberInfo, AddMembers, "AddMembers");
  GLADE_HOOKUP_OBJECT (EspaceAdminAddmemberInfo, DeleteMembers, "DeleteMembers");
  GLADE_HOOKUP_OBJECT (EspaceAdminAddmemberInfo, Settings, "Settings");
  GLADE_HOOKUP_OBJECT (EspaceAdminAddmemberInfo, label49, "label49");
  GLADE_HOOKUP_OBJECT (EspaceAdminAddmemberInfo, Home, "Home");
  GLADE_HOOKUP_OBJECT (EspaceAdminAddmemberInfo, Claims, "Claims");
  GLADE_HOOKUP_OBJECT (EspaceAdminAddmemberInfo, PromotionalCode, "PromotionalCode");
  GLADE_HOOKUP_OBJECT (EspaceAdminAddmemberInfo, Statistical, "Statistical");
  GLADE_HOOKUP_OBJECT (EspaceAdminAddmemberInfo, AddMembersUploadCV, "AddMembersUploadCV");
  GLADE_HOOKUP_OBJECT (EspaceAdminAddmemberInfo, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (EspaceAdminAddmemberInfo, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (EspaceAdminAddmemberInfo, image1, "image1");
  GLADE_HOOKUP_OBJECT (EspaceAdminAddmemberInfo, label73, "label73");
  GLADE_HOOKUP_OBJECT (EspaceAdminAddmemberInfo, AddMembersRole, "AddMembersRole");
  GLADE_HOOKUP_OBJECT (EspaceAdminAddmemberInfo, AddMembersAdd, "AddMembersAdd");
  GLADE_HOOKUP_OBJECT (EspaceAdminAddmemberInfo, label68, "label68");
  GLADE_HOOKUP_OBJECT (EspaceAdminAddmemberInfo, AddMembersEmptyInfo, "AddMembersEmptyInfo");
  GLADE_HOOKUP_OBJECT (EspaceAdminAddmemberInfo, AddMembersWrongPassword, "AddMembersWrongPassword");
  GLADE_HOOKUP_OBJECT (EspaceAdminAddmemberInfo, vseparator7, "vseparator7");

  return EspaceAdminAddmemberInfo;
}

GtkWidget*
create_EspaceAdminDeletemembersInfo (void)
{
  GtkWidget *EspaceAdminDeletemembersInfo;
  GtkWidget *fixed13;
  GtkWidget *vseparator9;
  GtkWidget *label63;
  GtkWidget *DeleteMemebersPassword;
  GtkWidget *DeleteMembersCPassword;
  GtkWidget *label64;
  GtkWidget *DeleteMembersWrongPassword;
  GtkWidget *Logout;
  GtkWidget *Statistical;
  GtkWidget *AddMembers;
  GtkWidget *DeleteMembers;
  GtkWidget *Settings;
  GtkWidget *label59;
  GtkWidget *Home;
  GtkWidget *Claims;
  GtkWidget *PromotionalCode;
  GtkWidget *hseparator9;
  GtkWidget *DeleteMembersChoose;
  GtkWidget *DeleteMembersText3;
  GtkWidget *DeleteMembersText2;
  GtkWidget *DeleteMembersNew;
  GtkWidget *label113;
  GtkWidget *label118;
  GtkWidget *label116;
  GtkWidget *label115;
  GtkWidget *label119;
  GtkWidget *label117;
  GtkWidget *DeleteMembersShowCV;
  GtkWidget *label127;
  GtkWidget *DeleteMembersError;
  GtkWidget *DeleteMembersOption;
  GtkWidget *DeleteMembersShow;
  GtkWidget *DeleteMembersActivate;
  GtkWidget *DeleteMembersDesactivate;
  GtkWidget *DeleteMembersApply;
  GtkWidget *label130;
  GtkWidget *label114;
  GtkWidget *DeleteMembersName;
  GtkWidget *DeleteMembersEmail;
  GtkWidget *DeleteMembersBirthDate;
  GtkWidget *DeleteMembersPhoneNumber;
  GtkWidget *DeleteMembersNationalID;
  GtkWidget *DeleteMembersPassword;
  GtkWidget *DeleteMembersStatus;
  GtkWidget *DeleteMembersRole;
  GtkWidget *DeleteMembersText1;

  EspaceAdminDeletemembersInfo = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (EspaceAdminDeletemembersInfo), _("Tunivist"));

  fixed13 = gtk_fixed_new ();
  gtk_widget_show (fixed13);
  gtk_container_add (GTK_CONTAINER (EspaceAdminDeletemembersInfo), fixed13);

  vseparator9 = gtk_vseparator_new ();
  gtk_widget_show (vseparator9);
  gtk_fixed_put (GTK_FIXED (fixed13), vseparator9, 232, 80);
  gtk_widget_set_size_request (vseparator9, 16, 448);

  label63 = gtk_label_new (_("Welcome Boss"));
  gtk_widget_show (label63);
  gtk_fixed_put (GTK_FIXED (fixed13), label63, 472, 8);
  gtk_widget_set_size_request (label63, 368, 40);
  gtk_misc_set_alignment (GTK_MISC (label63), 0.5, 0.49);

  DeleteMemebersPassword = gtk_entry_new ();
  gtk_widget_show (DeleteMemebersPassword);
  gtk_fixed_put (GTK_FIXED (fixed13), DeleteMemebersPassword, 920, 344);
  gtk_widget_set_size_request (DeleteMemebersPassword, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (DeleteMemebersPassword), 8226);

  DeleteMembersCPassword = gtk_entry_new ();
  gtk_widget_show (DeleteMembersCPassword);
  gtk_fixed_put (GTK_FIXED (fixed13), DeleteMembersCPassword, 920, 392);
  gtk_widget_set_size_request (DeleteMembersCPassword, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (DeleteMembersCPassword), 8226);

  label64 = gtk_label_new (_("Choose Admin/Agent:"));
  gtk_widget_show (label64);
  gtk_fixed_put (GTK_FIXED (fixed13), label64, 456, 136);
  gtk_widget_set_size_request (label64, 160, 32);

  DeleteMembersWrongPassword = gtk_label_new ("");
  gtk_widget_show (DeleteMembersWrongPassword);
  gtk_fixed_put (GTK_FIXED (fixed13), DeleteMembersWrongPassword, 608, 328);
  gtk_widget_set_size_request (DeleteMembersWrongPassword, 200, 24);

  Logout = gtk_button_new_with_mnemonic (_("Logout"));
  gtk_widget_show (Logout);
  gtk_fixed_put (GTK_FIXED (fixed13), Logout, 32, 16);
  gtk_widget_set_size_request (Logout, 68, 29);

  Statistical = gtk_button_new_with_mnemonic (_("Statistical"));
  gtk_widget_show (Statistical);
  gtk_fixed_put (GTK_FIXED (fixed13), Statistical, 40, 304);
  gtk_widget_set_size_request (Statistical, 144, 32);

  AddMembers = gtk_button_new_with_mnemonic (_("Add members"));
  gtk_widget_show (AddMembers);
  gtk_fixed_put (GTK_FIXED (fixed13), AddMembers, 40, 360);
  gtk_widget_set_size_request (AddMembers, 144, 32);

  DeleteMembers = gtk_button_new_with_mnemonic (_("Delete members"));
  gtk_widget_show (DeleteMembers);
  gtk_fixed_put (GTK_FIXED (fixed13), DeleteMembers, 40, 416);
  gtk_widget_set_size_request (DeleteMembers, 144, 32);

  Settings = gtk_button_new_with_mnemonic (_("Settings"));
  gtk_widget_show (Settings);
  gtk_fixed_put (GTK_FIXED (fixed13), Settings, 40, 472);
  gtk_widget_set_size_request (Settings, 144, 32);

  label59 = gtk_label_new (_("Dashboard"));
  gtk_widget_show (label59);
  gtk_fixed_put (GTK_FIXED (fixed13), label59, 56, 88);
  gtk_widget_set_size_request (label59, 120, 40);
  gtk_misc_set_alignment (GTK_MISC (label59), 0.49, 0.5);

  Home = gtk_button_new_with_mnemonic (_("Home"));
  gtk_widget_show (Home);
  gtk_fixed_put (GTK_FIXED (fixed13), Home, 40, 136);
  gtk_widget_set_size_request (Home, 144, 40);

  Claims = gtk_button_new_with_mnemonic (_("Claims"));
  gtk_widget_show (Claims);
  gtk_fixed_put (GTK_FIXED (fixed13), Claims, 40, 200);
  gtk_widget_set_size_request (Claims, 144, 32);

  PromotionalCode = gtk_button_new_with_mnemonic (_("Promotional code"));
  gtk_widget_show (PromotionalCode);
  gtk_fixed_put (GTK_FIXED (fixed13), PromotionalCode, 40, 248);
  gtk_widget_set_size_request (PromotionalCode, 144, 37);

  hseparator9 = gtk_hseparator_new ();
  gtk_widget_show (hseparator9);
  gtk_fixed_put (GTK_FIXED (fixed13), hseparator9, 0, 72);
  gtk_widget_set_size_request (hseparator9, 1168, 16);

  DeleteMembersChoose = gtk_combo_box_new_text ();
  gtk_widget_show (DeleteMembersChoose);
  gtk_fixed_put (GTK_FIXED (fixed13), DeleteMembersChoose, 631, 136);
  gtk_widget_set_size_request (DeleteMembersChoose, 181, 31);

  DeleteMembersText3 = gtk_label_new (_("Confirm Password:"));
  gtk_widget_show (DeleteMembersText3);
  gtk_fixed_put (GTK_FIXED (fixed13), DeleteMembersText3, 768, 392);
  gtk_widget_set_size_request (DeleteMembersText3, 144, 24);

  DeleteMembersText2 = gtk_label_new (_("Password:"));
  gtk_widget_show (DeleteMembersText2);
  gtk_fixed_put (GTK_FIXED (fixed13), DeleteMembersText2, 824, 344);
  gtk_widget_set_size_request (DeleteMembersText2, 96, 24);

  DeleteMembersNew = gtk_entry_new ();
  gtk_widget_show (DeleteMembersNew);
  gtk_fixed_put (GTK_FIXED (fixed13), DeleteMembersNew, 920, 280);
  gtk_widget_set_size_request (DeleteMembersNew, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (DeleteMembersNew), 8226);

  label113 = gtk_label_new (_("Choose Modification:"));
  gtk_widget_show (label113);
  gtk_fixed_put (GTK_FIXED (fixed13), label113, 752, 216);
  gtk_widget_set_size_request (label113, 152, 16);

  label118 = gtk_label_new (_("Birth date:"));
  gtk_widget_show (label118);
  gtk_fixed_put (GTK_FIXED (fixed13), label118, 272, 280);
  gtk_widget_set_size_request (label118, 88, 16);

  label116 = gtk_label_new (_("Phone number:"));
  gtk_widget_show (label116);
  gtk_fixed_put (GTK_FIXED (fixed13), label116, 240, 320);
  gtk_widget_set_size_request (label116, 120, 16);

  label115 = gtk_label_new (_("Email:"));
  gtk_widget_show (label115);
  gtk_fixed_put (GTK_FIXED (fixed13), label115, 304, 240);
  gtk_widget_set_size_request (label115, 57, 17);

  label119 = gtk_label_new (_("Password:"));
  gtk_widget_show (label119);
  gtk_fixed_put (GTK_FIXED (fixed13), label119, 272, 400);
  gtk_widget_set_size_request (label119, 89, 16);

  label117 = gtk_label_new (_("National ID:"));
  gtk_widget_show (label117);
  gtk_fixed_put (GTK_FIXED (fixed13), label117, 264, 360);
  gtk_widget_set_size_request (label117, 104, 16);

  DeleteMembersShowCV = gtk_button_new_with_mnemonic (_("Show CV"));
  gtk_widget_show (DeleteMembersShowCV);
  gtk_fixed_put (GTK_FIXED (fixed13), DeleteMembersShowCV, 432, 472);
  gtk_widget_set_size_request (DeleteMembersShowCV, 72, 24);

  label127 = gtk_label_new (_("Status:"));
  gtk_widget_show (label127);
  gtk_fixed_put (GTK_FIXED (fixed13), label127, 296, 440);
  gtk_widget_set_size_request (label127, 65, 16);

  DeleteMembersError = gtk_label_new ("");
  gtk_widget_show (DeleteMembersError);
  gtk_fixed_put (GTK_FIXED (fixed13), DeleteMembersError, 920, 432);
  gtk_widget_set_size_request (DeleteMembersError, 160, 16);

  DeleteMembersOption = gtk_combo_box_new_text ();
  gtk_widget_show (DeleteMembersOption);
  gtk_fixed_put (GTK_FIXED (fixed13), DeleteMembersOption, 920, 208);
  gtk_widget_set_size_request (DeleteMembersOption, 176, 32);

  DeleteMembersShow = gtk_button_new_with_mnemonic (_("Show"));
  gtk_widget_show (DeleteMembersShow);
  gtk_fixed_put (GTK_FIXED (fixed13), DeleteMembersShow, 560, 392);
  gtk_widget_set_size_request (DeleteMembersShow, 56, 32);

  DeleteMembersActivate = gtk_button_new_with_mnemonic (_("Activate"));
  gtk_widget_show (DeleteMembersActivate);
  gtk_fixed_put (GTK_FIXED (fixed13), DeleteMembersActivate, 920, 136);
  gtk_widget_set_size_request (DeleteMembersActivate, 80, 32);

  DeleteMembersDesactivate = gtk_button_new_with_mnemonic (_("Desactivate"));
  gtk_widget_show (DeleteMembersDesactivate);
  gtk_fixed_put (GTK_FIXED (fixed13), DeleteMembersDesactivate, 816, 136);
  gtk_widget_set_size_request (DeleteMembersDesactivate, 96, 32);

  DeleteMembersApply = gtk_button_new_with_mnemonic (_("Apply"));
  gtk_widget_show (DeleteMembersApply);
  gtk_fixed_put (GTK_FIXED (fixed13), DeleteMembersApply, 976, 456);
  gtk_widget_set_size_request (DeleteMembersApply, 68, 29);

  label130 = gtk_label_new (_("Role:"));
  gtk_widget_show (label130);
  gtk_fixed_put (GTK_FIXED (fixed13), label130, 304, 176);
  gtk_widget_set_size_request (label130, 57, 17);

  label114 = gtk_label_new (_("Full name:"));
  gtk_widget_show (label114);
  gtk_fixed_put (GTK_FIXED (fixed13), label114, 272, 208);
  gtk_widget_set_size_request (label114, 89, 16);

  DeleteMembersName = gtk_label_new ("");
  gtk_widget_show (DeleteMembersName);
  gtk_fixed_put (GTK_FIXED (fixed13), DeleteMembersName, 360, 208);
  gtk_widget_set_size_request (DeleteMembersName, 184, 16);

  DeleteMembersEmail = gtk_label_new ("");
  gtk_widget_show (DeleteMembersEmail);
  gtk_fixed_put (GTK_FIXED (fixed13), DeleteMembersEmail, 360, 240);
  gtk_widget_set_size_request (DeleteMembersEmail, 208, 16);

  DeleteMembersBirthDate = gtk_label_new ("");
  gtk_widget_show (DeleteMembersBirthDate);
  gtk_fixed_put (GTK_FIXED (fixed13), DeleteMembersBirthDate, 368, 280);
  gtk_widget_set_size_request (DeleteMembersBirthDate, 200, 16);

  DeleteMembersPhoneNumber = gtk_label_new ("");
  gtk_widget_show (DeleteMembersPhoneNumber);
  gtk_fixed_put (GTK_FIXED (fixed13), DeleteMembersPhoneNumber, 368, 320);
  gtk_widget_set_size_request (DeleteMembersPhoneNumber, 200, 16);

  DeleteMembersNationalID = gtk_label_new ("");
  gtk_widget_show (DeleteMembersNationalID);
  gtk_fixed_put (GTK_FIXED (fixed13), DeleteMembersNationalID, 368, 360);
  gtk_widget_set_size_request (DeleteMembersNationalID, 200, 16);

  DeleteMembersPassword = gtk_label_new (_("*******"));
  gtk_widget_show (DeleteMembersPassword);
  gtk_fixed_put (GTK_FIXED (fixed13), DeleteMembersPassword, 368, 400);
  gtk_widget_set_size_request (DeleteMembersPassword, 192, 16);

  DeleteMembersStatus = gtk_label_new ("");
  gtk_widget_show (DeleteMembersStatus);
  gtk_fixed_put (GTK_FIXED (fixed13), DeleteMembersStatus, 368, 440);
  gtk_widget_set_size_request (DeleteMembersStatus, 200, 16);

  DeleteMembersRole = gtk_label_new ("");
  gtk_widget_show (DeleteMembersRole);
  gtk_fixed_put (GTK_FIXED (fixed13), DeleteMembersRole, 376, 176);
  gtk_widget_set_size_request (DeleteMembersRole, 152, 16);

  DeleteMembersText1 = gtk_label_new (_("New Info:"));
  gtk_widget_show (DeleteMembersText1);
  gtk_fixed_put (GTK_FIXED (fixed13), DeleteMembersText1, 824, 280);
  gtk_widget_set_size_request (DeleteMembersText1, 89, 24);

  g_signal_connect ((gpointer) EspaceAdminDeletemembersInfo, "show",
                    G_CALLBACK (on_EspaceAdminDeletemembersInfo_show),
                    NULL);
  g_signal_connect ((gpointer) Logout, "clicked",
                    G_CALLBACK (on_Logout_clicked),
                    NULL);
  g_signal_connect ((gpointer) Statistical, "clicked",
                    G_CALLBACK (on_Statistical_clicked),
                    NULL);
  g_signal_connect ((gpointer) AddMembers, "clicked",
                    G_CALLBACK (on_AddMembers_clicked),
                    NULL);
  g_signal_connect ((gpointer) Settings, "clicked",
                    G_CALLBACK (on_Settings_clicked),
                    NULL);
  g_signal_connect ((gpointer) Home, "clicked",
                    G_CALLBACK (on_Home_clicked),
                    NULL);
  g_signal_connect ((gpointer) PromotionalCode, "clicked",
                    G_CALLBACK (on_PromotionalCode_clicked),
                    NULL);
  g_signal_connect ((gpointer) DeleteMembersChoose, "changed",
                    G_CALLBACK (on_DeleteMembersChoose_changed),
                    NULL);
  g_signal_connect ((gpointer) DeleteMembersShowCV, "clicked",
                    G_CALLBACK (on_DeleteMembersShowCV_clicked),
                    NULL);
  g_signal_connect ((gpointer) DeleteMembersShow, "clicked",
                    G_CALLBACK (on_DeleteMembersShow_clicked),
                    NULL);
  g_signal_connect ((gpointer) DeleteMembersActivate, "clicked",
                    G_CALLBACK (on_DeleteMembersActivate_clicked),
                    NULL);
  g_signal_connect ((gpointer) DeleteMembersDesactivate, "clicked",
                    G_CALLBACK (on_DeleteMembersDesactivate_clicked),
                    NULL);
  g_signal_connect ((gpointer) DeleteMembersApply, "clicked",
                    G_CALLBACK (on_DeleteMembersApply_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (EspaceAdminDeletemembersInfo, EspaceAdminDeletemembersInfo, "EspaceAdminDeletemembersInfo");
  GLADE_HOOKUP_OBJECT (EspaceAdminDeletemembersInfo, fixed13, "fixed13");
  GLADE_HOOKUP_OBJECT (EspaceAdminDeletemembersInfo, vseparator9, "vseparator9");
  GLADE_HOOKUP_OBJECT (EspaceAdminDeletemembersInfo, label63, "label63");
  GLADE_HOOKUP_OBJECT (EspaceAdminDeletemembersInfo, DeleteMemebersPassword, "DeleteMemebersPassword");
  GLADE_HOOKUP_OBJECT (EspaceAdminDeletemembersInfo, DeleteMembersCPassword, "DeleteMembersCPassword");
  GLADE_HOOKUP_OBJECT (EspaceAdminDeletemembersInfo, label64, "label64");
  GLADE_HOOKUP_OBJECT (EspaceAdminDeletemembersInfo, DeleteMembersWrongPassword, "DeleteMembersWrongPassword");
  GLADE_HOOKUP_OBJECT (EspaceAdminDeletemembersInfo, Logout, "Logout");
  GLADE_HOOKUP_OBJECT (EspaceAdminDeletemembersInfo, Statistical, "Statistical");
  GLADE_HOOKUP_OBJECT (EspaceAdminDeletemembersInfo, AddMembers, "AddMembers");
  GLADE_HOOKUP_OBJECT (EspaceAdminDeletemembersInfo, DeleteMembers, "DeleteMembers");
  GLADE_HOOKUP_OBJECT (EspaceAdminDeletemembersInfo, Settings, "Settings");
  GLADE_HOOKUP_OBJECT (EspaceAdminDeletemembersInfo, label59, "label59");
  GLADE_HOOKUP_OBJECT (EspaceAdminDeletemembersInfo, Home, "Home");
  GLADE_HOOKUP_OBJECT (EspaceAdminDeletemembersInfo, Claims, "Claims");
  GLADE_HOOKUP_OBJECT (EspaceAdminDeletemembersInfo, PromotionalCode, "PromotionalCode");
  GLADE_HOOKUP_OBJECT (EspaceAdminDeletemembersInfo, hseparator9, "hseparator9");
  GLADE_HOOKUP_OBJECT (EspaceAdminDeletemembersInfo, DeleteMembersChoose, "DeleteMembersChoose");
  GLADE_HOOKUP_OBJECT (EspaceAdminDeletemembersInfo, DeleteMembersText3, "DeleteMembersText3");
  GLADE_HOOKUP_OBJECT (EspaceAdminDeletemembersInfo, DeleteMembersText2, "DeleteMembersText2");
  GLADE_HOOKUP_OBJECT (EspaceAdminDeletemembersInfo, DeleteMembersNew, "DeleteMembersNew");
  GLADE_HOOKUP_OBJECT (EspaceAdminDeletemembersInfo, label113, "label113");
  GLADE_HOOKUP_OBJECT (EspaceAdminDeletemembersInfo, label118, "label118");
  GLADE_HOOKUP_OBJECT (EspaceAdminDeletemembersInfo, label116, "label116");
  GLADE_HOOKUP_OBJECT (EspaceAdminDeletemembersInfo, label115, "label115");
  GLADE_HOOKUP_OBJECT (EspaceAdminDeletemembersInfo, label119, "label119");
  GLADE_HOOKUP_OBJECT (EspaceAdminDeletemembersInfo, label117, "label117");
  GLADE_HOOKUP_OBJECT (EspaceAdminDeletemembersInfo, DeleteMembersShowCV, "DeleteMembersShowCV");
  GLADE_HOOKUP_OBJECT (EspaceAdminDeletemembersInfo, label127, "label127");
  GLADE_HOOKUP_OBJECT (EspaceAdminDeletemembersInfo, DeleteMembersError, "DeleteMembersError");
  GLADE_HOOKUP_OBJECT (EspaceAdminDeletemembersInfo, DeleteMembersOption, "DeleteMembersOption");
  GLADE_HOOKUP_OBJECT (EspaceAdminDeletemembersInfo, DeleteMembersShow, "DeleteMembersShow");
  GLADE_HOOKUP_OBJECT (EspaceAdminDeletemembersInfo, DeleteMembersActivate, "DeleteMembersActivate");
  GLADE_HOOKUP_OBJECT (EspaceAdminDeletemembersInfo, DeleteMembersDesactivate, "DeleteMembersDesactivate");
  GLADE_HOOKUP_OBJECT (EspaceAdminDeletemembersInfo, DeleteMembersApply, "DeleteMembersApply");
  GLADE_HOOKUP_OBJECT (EspaceAdminDeletemembersInfo, label130, "label130");
  GLADE_HOOKUP_OBJECT (EspaceAdminDeletemembersInfo, label114, "label114");
  GLADE_HOOKUP_OBJECT (EspaceAdminDeletemembersInfo, DeleteMembersName, "DeleteMembersName");
  GLADE_HOOKUP_OBJECT (EspaceAdminDeletemembersInfo, DeleteMembersEmail, "DeleteMembersEmail");
  GLADE_HOOKUP_OBJECT (EspaceAdminDeletemembersInfo, DeleteMembersBirthDate, "DeleteMembersBirthDate");
  GLADE_HOOKUP_OBJECT (EspaceAdminDeletemembersInfo, DeleteMembersPhoneNumber, "DeleteMembersPhoneNumber");
  GLADE_HOOKUP_OBJECT (EspaceAdminDeletemembersInfo, DeleteMembersNationalID, "DeleteMembersNationalID");
  GLADE_HOOKUP_OBJECT (EspaceAdminDeletemembersInfo, DeleteMembersPassword, "DeleteMembersPassword");
  GLADE_HOOKUP_OBJECT (EspaceAdminDeletemembersInfo, DeleteMembersStatus, "DeleteMembersStatus");
  GLADE_HOOKUP_OBJECT (EspaceAdminDeletemembersInfo, DeleteMembersRole, "DeleteMembersRole");
  GLADE_HOOKUP_OBJECT (EspaceAdminDeletemembersInfo, DeleteMembersText1, "DeleteMembersText1");

  return EspaceAdminDeletemembersInfo;
}

GtkWidget*
create_windowuploadcv (void)
{
  GtkWidget *windowuploadcv;
  GtkWidget *dialog_vbox1;
  GtkWidget *dialog_action_area1;
  GtkWidget *AddMembersUploadCancel;
  GtkWidget *AddMembersUploadOpen;

  windowuploadcv = gtk_file_chooser_dialog_new ("", NULL, GTK_FILE_CHOOSER_ACTION_OPEN, NULL);
  gtk_container_set_border_width (GTK_CONTAINER (windowuploadcv), 5);
  gtk_window_set_role (GTK_WINDOW (windowuploadcv), "GtkFileChooserDialog");
  gtk_window_set_type_hint (GTK_WINDOW (windowuploadcv), GDK_WINDOW_TYPE_HINT_DIALOG);

  dialog_vbox1 = GTK_DIALOG (windowuploadcv)->vbox;
  gtk_widget_show (dialog_vbox1);

  dialog_action_area1 = GTK_DIALOG (windowuploadcv)->action_area;
  gtk_widget_show (dialog_action_area1);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area1), GTK_BUTTONBOX_END);

  AddMembersUploadCancel = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (AddMembersUploadCancel);
  gtk_dialog_add_action_widget (GTK_DIALOG (windowuploadcv), AddMembersUploadCancel, GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (AddMembersUploadCancel, GTK_CAN_DEFAULT);

  AddMembersUploadOpen = gtk_button_new_from_stock ("gtk-open");
  gtk_widget_show (AddMembersUploadOpen);
  gtk_dialog_add_action_widget (GTK_DIALOG (windowuploadcv), AddMembersUploadOpen, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (AddMembersUploadOpen, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) AddMembersUploadCancel, "clicked",
                    G_CALLBACK (on_AddMembersUploadCancel_clicked),
                    NULL);
  g_signal_connect ((gpointer) AddMembersUploadOpen, "clicked",
                    G_CALLBACK (on_AddMembersUploadOpen_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (windowuploadcv, windowuploadcv, "windowuploadcv");
  GLADE_HOOKUP_OBJECT_NO_REF (windowuploadcv, dialog_vbox1, "dialog_vbox1");
  GLADE_HOOKUP_OBJECT_NO_REF (windowuploadcv, dialog_action_area1, "dialog_action_area1");
  GLADE_HOOKUP_OBJECT (windowuploadcv, AddMembersUploadCancel, "AddMembersUploadCancel");
  GLADE_HOOKUP_OBJECT (windowuploadcv, AddMembersUploadOpen, "AddMembersUploadOpen");

  gtk_widget_grab_default (AddMembersUploadOpen);
  return windowuploadcv;
}

GtkWidget*
create_EspaceAdminPromotionalCode (void)
{
  GtkWidget *EspaceAdminPromotionalCode;
  GtkWidget *fixed14;
  GtkWidget *vseparator10;
  GtkWidget *label105;
  GtkWidget *hseparator10;
  GtkWidget *Home;
  GtkWidget *Claims;
  GtkWidget *PromotionalCode;
  GtkWidget *AddMembers;
  GtkWidget *DeleteMembers;
  GtkWidget *Settings;
  GtkWidget *Logout;
  GtkWidget *label109;
  GtkWidget *PCCode;
  GtkWidget *PCChooseCode;
  GtkWidget *label111;
  GtkWidget *label110;
  GtkWidget *PCMessageText;
  GtkWidget *PCCodeText;
  GtkWidget *label106;
  GtkWidget *PCChooseClient;
  GtkWidget *PCGenerateCode;
  GtkWidget *PCAdd;
  GtkWidget *PCSend;
  GtkWidget *Statistical;
  GtkWidget *PCCodeCheck;
  GtkWidget *PCDelete;

  EspaceAdminPromotionalCode = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (EspaceAdminPromotionalCode), _("Tunivist"));

  fixed14 = gtk_fixed_new ();
  gtk_widget_show (fixed14);
  gtk_container_add (GTK_CONTAINER (EspaceAdminPromotionalCode), fixed14);

  vseparator10 = gtk_vseparator_new ();
  gtk_widget_show (vseparator10);
  gtk_fixed_put (GTK_FIXED (fixed14), vseparator10, 232, 80);
  gtk_widget_set_size_request (vseparator10, 16, 448);

  label105 = gtk_label_new (_("Dashboard"));
  gtk_widget_show (label105);
  gtk_fixed_put (GTK_FIXED (fixed14), label105, 56, 88);
  gtk_widget_set_size_request (label105, 120, 40);
  gtk_misc_set_alignment (GTK_MISC (label105), 0.49, 0.5);

  hseparator10 = gtk_hseparator_new ();
  gtk_widget_show (hseparator10);
  gtk_fixed_put (GTK_FIXED (fixed14), hseparator10, 0, 72);
  gtk_widget_set_size_request (hseparator10, 1168, 16);

  Home = gtk_button_new_with_mnemonic (_("Home"));
  gtk_widget_show (Home);
  gtk_fixed_put (GTK_FIXED (fixed14), Home, 40, 136);
  gtk_widget_set_size_request (Home, 144, 40);

  Claims = gtk_button_new_with_mnemonic (_("Claims"));
  gtk_widget_show (Claims);
  gtk_fixed_put (GTK_FIXED (fixed14), Claims, 40, 200);
  gtk_widget_set_size_request (Claims, 144, 32);

  PromotionalCode = gtk_button_new_with_mnemonic (_("Promotional code"));
  gtk_widget_show (PromotionalCode);
  gtk_fixed_put (GTK_FIXED (fixed14), PromotionalCode, 40, 248);
  gtk_widget_set_size_request (PromotionalCode, 144, 40);

  AddMembers = gtk_button_new_with_mnemonic (_("Add members"));
  gtk_widget_show (AddMembers);
  gtk_fixed_put (GTK_FIXED (fixed14), AddMembers, 40, 360);
  gtk_widget_set_size_request (AddMembers, 144, 32);

  DeleteMembers = gtk_button_new_with_mnemonic (_("Delete members"));
  gtk_widget_show (DeleteMembers);
  gtk_fixed_put (GTK_FIXED (fixed14), DeleteMembers, 40, 416);
  gtk_widget_set_size_request (DeleteMembers, 144, 32);

  Settings = gtk_button_new_with_mnemonic (_("Settings"));
  gtk_widget_show (Settings);
  gtk_fixed_put (GTK_FIXED (fixed14), Settings, 40, 472);
  gtk_widget_set_size_request (Settings, 144, 32);

  Logout = gtk_button_new_with_mnemonic (_("Logout"));
  gtk_widget_show (Logout);
  gtk_fixed_put (GTK_FIXED (fixed14), Logout, 32, 16);
  gtk_widget_set_size_request (Logout, 68, 29);

  label109 = gtk_label_new (_("Codes in Database"));
  gtk_widget_show (label109);
  gtk_fixed_put (GTK_FIXED (fixed14), label109, 336, 96);
  gtk_widget_set_size_request (label109, 153, 16);

  PCCode = gtk_label_new (_("**********"));
  gtk_widget_show (PCCode);
  gtk_fixed_put (GTK_FIXED (fixed14), PCCode, 312, 368);
  gtk_widget_set_size_request (PCCode, 176, 32);

  PCChooseCode = gtk_combo_box_new_text ();
  gtk_widget_show (PCChooseCode);
  gtk_fixed_put (GTK_FIXED (fixed14), PCChooseCode, 856, 120);
  gtk_widget_set_size_request (PCChooseCode, 200, 32);

  label111 = gtk_label_new (_("Choose a client"));
  gtk_widget_show (label111);
  gtk_fixed_put (GTK_FIXED (fixed14), label111, 720, 192);
  gtk_widget_set_size_request (label111, 129, 16);

  label110 = gtk_label_new (_("Choose a code"));
  gtk_widget_show (label110);
  gtk_fixed_put (GTK_FIXED (fixed14), label110, 728, 128);
  gtk_widget_set_size_request (label110, 113, 16);

  PCMessageText = gtk_entry_new ();
  gtk_widget_show (PCMessageText);
  gtk_fixed_put (GTK_FIXED (fixed14), PCMessageText, 728, 248);
  gtk_widget_set_size_request (PCMessageText, 376, 160);
  gtk_entry_set_text (GTK_ENTRY (PCMessageText), _("Write a message.."));
  gtk_entry_set_invisible_char (GTK_ENTRY (PCMessageText), 8226);

  PCCodeText = gtk_label_new (_("*"));
  gtk_widget_show (PCCodeText);
  gtk_fixed_put (GTK_FIXED (fixed14), PCCodeText, 296, 128);
  gtk_widget_set_size_request (PCCodeText, 232, 208);

  label106 = gtk_label_new (_("Welcome Boss"));
  gtk_widget_show (label106);
  gtk_fixed_put (GTK_FIXED (fixed14), label106, 472, 8);
  gtk_widget_set_size_request (label106, 368, 40);
  gtk_misc_set_alignment (GTK_MISC (label106), 0.5, 0.49);

  PCChooseClient = gtk_combo_box_new_text ();
  gtk_widget_show (PCChooseClient);
  gtk_fixed_put (GTK_FIXED (fixed14), PCChooseClient, 856, 184);
  gtk_widget_set_size_request (PCChooseClient, 200, 31);

  PCGenerateCode = gtk_button_new_with_mnemonic (_("Generate code"));
  gtk_widget_show (PCGenerateCode);
  gtk_fixed_put (GTK_FIXED (fixed14), PCGenerateCode, 272, 408);
  gtk_widget_set_size_request (PCGenerateCode, 120, 40);

  PCAdd = gtk_button_new_with_mnemonic (_("Add to Database"));
  gtk_widget_show (PCAdd);
  gtk_fixed_put (GTK_FIXED (fixed14), PCAdd, 416, 408);
  gtk_widget_set_size_request (PCAdd, 128, 40);

  PCSend = gtk_button_new_with_mnemonic (_("Send"));
  gtk_widget_show (PCSend);
  gtk_fixed_put (GTK_FIXED (fixed14), PCSend, 888, 432);
  gtk_widget_set_size_request (PCSend, 68, 29);

  Statistical = gtk_button_new_with_mnemonic (_("Statistical"));
  gtk_widget_show (Statistical);
  gtk_fixed_put (GTK_FIXED (fixed14), Statistical, 40, 304);
  gtk_widget_set_size_request (Statistical, 144, 32);

  PCCodeCheck = gtk_label_new ("");
  gtk_widget_show (PCCodeCheck);
  gtk_fixed_put (GTK_FIXED (fixed14), PCCodeCheck, 312, 464);
  gtk_widget_set_size_request (PCCodeCheck, 176, 16);

  PCDelete = gtk_button_new_with_mnemonic (_("Delete"));
  gtk_widget_show (PCDelete);
  gtk_fixed_put (GTK_FIXED (fixed14), PCDelete, 1064, 120);
  gtk_widget_set_size_request (PCDelete, 64, 32);

  g_signal_connect ((gpointer) EspaceAdminPromotionalCode, "show",
                    G_CALLBACK (on_EspaceAdminPromotionalCode_show),
                    NULL);
  g_signal_connect ((gpointer) Home, "clicked",
                    G_CALLBACK (on_Home_clicked),
                    NULL);
  g_signal_connect ((gpointer) Claims, "clicked",
                    G_CALLBACK (on_Claims_clicked),
                    NULL);
  g_signal_connect ((gpointer) PromotionalCode, "clicked",
                    G_CALLBACK (on_PromotionalCode_clicked),
                    NULL);
  g_signal_connect ((gpointer) AddMembers, "clicked",
                    G_CALLBACK (on_AddMembers_clicked),
                    NULL);
  g_signal_connect ((gpointer) DeleteMembers, "clicked",
                    G_CALLBACK (on_DeleteMembers_clicked),
                    NULL);
  g_signal_connect ((gpointer) Settings, "clicked",
                    G_CALLBACK (on_Settings_clicked),
                    NULL);
  g_signal_connect ((gpointer) Logout, "clicked",
                    G_CALLBACK (on_Logout_clicked),
                    NULL);
  g_signal_connect ((gpointer) PCGenerateCode, "clicked",
                    G_CALLBACK (on_PCGenerateCode_clicked),
                    NULL);
  g_signal_connect ((gpointer) PCAdd, "clicked",
                    G_CALLBACK (on_PCAdd_clicked),
                    NULL);
  g_signal_connect ((gpointer) PCSend, "clicked",
                    G_CALLBACK (on_PCSend_clicked),
                    NULL);
  g_signal_connect ((gpointer) Statistical, "clicked",
                    G_CALLBACK (on_Statistical_clicked),
                    NULL);
  g_signal_connect ((gpointer) PCDelete, "clicked",
                    G_CALLBACK (on_PCDelete_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (EspaceAdminPromotionalCode, EspaceAdminPromotionalCode, "EspaceAdminPromotionalCode");
  GLADE_HOOKUP_OBJECT (EspaceAdminPromotionalCode, fixed14, "fixed14");
  GLADE_HOOKUP_OBJECT (EspaceAdminPromotionalCode, vseparator10, "vseparator10");
  GLADE_HOOKUP_OBJECT (EspaceAdminPromotionalCode, label105, "label105");
  GLADE_HOOKUP_OBJECT (EspaceAdminPromotionalCode, hseparator10, "hseparator10");
  GLADE_HOOKUP_OBJECT (EspaceAdminPromotionalCode, Home, "Home");
  GLADE_HOOKUP_OBJECT (EspaceAdminPromotionalCode, Claims, "Claims");
  GLADE_HOOKUP_OBJECT (EspaceAdminPromotionalCode, PromotionalCode, "PromotionalCode");
  GLADE_HOOKUP_OBJECT (EspaceAdminPromotionalCode, AddMembers, "AddMembers");
  GLADE_HOOKUP_OBJECT (EspaceAdminPromotionalCode, DeleteMembers, "DeleteMembers");
  GLADE_HOOKUP_OBJECT (EspaceAdminPromotionalCode, Settings, "Settings");
  GLADE_HOOKUP_OBJECT (EspaceAdminPromotionalCode, Logout, "Logout");
  GLADE_HOOKUP_OBJECT (EspaceAdminPromotionalCode, label109, "label109");
  GLADE_HOOKUP_OBJECT (EspaceAdminPromotionalCode, PCCode, "PCCode");
  GLADE_HOOKUP_OBJECT (EspaceAdminPromotionalCode, PCChooseCode, "PCChooseCode");
  GLADE_HOOKUP_OBJECT (EspaceAdminPromotionalCode, label111, "label111");
  GLADE_HOOKUP_OBJECT (EspaceAdminPromotionalCode, label110, "label110");
  GLADE_HOOKUP_OBJECT (EspaceAdminPromotionalCode, PCMessageText, "PCMessageText");
  GLADE_HOOKUP_OBJECT (EspaceAdminPromotionalCode, PCCodeText, "PCCodeText");
  GLADE_HOOKUP_OBJECT (EspaceAdminPromotionalCode, label106, "label106");
  GLADE_HOOKUP_OBJECT (EspaceAdminPromotionalCode, PCChooseClient, "PCChooseClient");
  GLADE_HOOKUP_OBJECT (EspaceAdminPromotionalCode, PCGenerateCode, "PCGenerateCode");
  GLADE_HOOKUP_OBJECT (EspaceAdminPromotionalCode, PCAdd, "PCAdd");
  GLADE_HOOKUP_OBJECT (EspaceAdminPromotionalCode, PCSend, "PCSend");
  GLADE_HOOKUP_OBJECT (EspaceAdminPromotionalCode, Statistical, "Statistical");
  GLADE_HOOKUP_OBJECT (EspaceAdminPromotionalCode, PCCodeCheck, "PCCodeCheck");
  GLADE_HOOKUP_OBJECT (EspaceAdminPromotionalCode, PCDelete, "PCDelete");

  return EspaceAdminPromotionalCode;
}

