/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_catalogue_customer (void);
GtkWidget* create_catalogue_agent (void);
GtkWidget* create_sign_up (void);
GtkWidget* create_email_pswd (void);
GtkWidget* create_forgot_psswd (void);
GtkWidget* create_menu_customer (void);
GtkWidget* create_settings (void);
GtkWidget* create_deleteyouraccount (void);
GtkWidget* create_change_your_picture (void);
GtkWidget* create_protect_your_account (void);
GtkWidget* create_Hotel (void);
GtkWidget* create_leasing (void);
GtkWidget* create_offer_of_the_day (void);
GtkWidget* create_catalogue_customer_view (void);
GtkWidget* create_catalogue_customer_download (void);
GtkWidget* create_image1 (void);
