/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_book_flight (void);
GtkWidget* create_book_hotel (void);
GtkWidget* create_book_car (void);
GtkWidget* create_History (void);
GtkWidget* create_principale (void);
